
When any country or state approves the trading of carbon credits (along
with the carbon claims associated with them), Regen Registry will adhere
to guidelines as established by the United Nations Framework Convention
on Climate Change
(UNFCCC)footnote:[https://unfccc.int/[[.underline]#https://unfccc.int/#]]
and Carbon Offsetting and Reduction Scheme for International Aviation
(CORSIA)footnote:[https://www.icao.int/environmental-protection/CORSIA/Pages/default.aspx[[.underline]#https://www.icao.int/environmental-protection/CORSIA/Pages/default.aspx#]]
to prevent double counting towards NDC and CORSIA obligations
respectively, and to ensure the environmental integrity of emissions
reductions.
____

== Verification

____
This section provides a general overview of the requirements for ex post
verification of GHG and Co-Benefits assertions by an independent
third-party verifier approved by Regen Registry.

As defined in this section, verification will be conducted by an
independent verifier chosen by the Project Proponent and approved by
Regen Registry.

Regen Registry seeks a balance between adequate assurances, the
overhead, and costs associated with verification. Therefore, each Credit
Class can stipulate the requirements that are best suited to the
ecosystem, best management practice and/or locale(s) it pertains to.
Regen Registry retains the right to adapt the requirements and provide
verification templates/interfaces as needed.
____

=== *Definitions*

[arabic, start=12]
. {blank}
+
____
Validation is the systematic, independent, and documented process for
the evaluation of the reasonableness of the assumptions, limitations,
and methods that support a statement about future (ex-ante) GHG and
Co-Benefits outcomes.
____
. {blank}
+
____
Verification is the systematic, independent, and documented assessment
by a qualified ,impartial third-party of the GHG and Co-Benefits
assertion for a specific reporting period.
____
. {blank}
+
____
Regen Registry does not require an ex-ante GHG estimate in the Project
Plan and therefore validation is not necessary. Instead, the verifier
validates the project eligibility according to the rules defined in the
Program Guide, Credit Class and the Approved Methodology. Regen Registry
has simplified the eligibility requirements and considers verification
an applicable standard. However, each Credit Class can customize the
requirements as needed and add validation.
____

=== *Verifier Requirements*

[arabic, start=15]
. {blank}
+
____
The Project Proponent can choose a verifier from either of the following
options:
____
[arabic]
.. {blank}
+
____
Verification bodies accredited under ISO 14065 and in good standing with
their relevant ISO member body.
____
.. {blank}
+
____
Verifiers approved by Established Registries.
____
.. {blank}
+
____
Verifiers that satisfy these minimum requirements:
____
[arabic]
... {blank}
+
____
Have sufficient proof of identity.
____
... {blank}
+
____
Obtain Errors & Omissions Insurance for at least $1 million.
____
... {blank}
+
____
Has demonstrated technical expertise in agriculture and grazing.
____
... {blank}
+
____
Be in a position of fiduciary duty.
____
.. {blank}
+
____
Verifiers that are accredited under ISO 14065 (per article 10.2.1.1)
and/or approved by Established Registries are automatically approved to
be verifiers on Regen Registry. Other verifiers must submit an
application for consideration. A list of approved verifiers will be made
available on the Regen Registry website.
____
.. {blank}
+
____
In order to increase the assurance level in projects, Project Proponents
shall engage at least two lead verifiers over the lifetime of their
project, where the final project verification is done by a different
verifier than the one used in prior verification events.
____
.. {blank}
+
____
Verifiers must sign a statement confirming their lack of conflict of
interest with the Project Proponent. Regen Registry and the Project
Proponent must be satisfied that any potential for conflict of interest
can be mitigated. To limit the potential for conflict of interest, these
restrictions are put in place:
____
[arabic]
... {blank}
+
____
Verifiers will not conduct a verification for any project in which:
____
[arabic]
.... {blank}
+
____
Any member of the verification team has a financial interest in the
project or the Project Proponent.
____
.... {blank}
+
____
The Verifier has played a role in developing the project.
____
... {blank}
+
____
The verifier will disclose all relationships, such as familial or
fiduciary, within the past three years between the Verifier on the one
hand, and the project and Project Proponent on the other.
____

=== *Payment for Verification*

[arabic, start=16]
. {blank}
+
____
Project Proponent is responsible for engaging and paying for
verifications.
____

=== *Evidence Gathering*

[arabic, start=17]
. {blank}
+
____
Verifier shall take necessary and appropriate steps to assure the
project inputs are authentic, using a random sampling approach whenever
appropriate. Verifiers will adhere to the Regen Registry data privacy
policy to ensure Project Proponent maintains privacy of their data.
____
. {blank}
+
____
Verifiers are required to provide assurance as to the reasonableness and
accuracy of the data the Project Proponent has provided to Regen
Registry and the Monitor, but they are not asked to attest to the
validity or accuracy of the outputs of the Monitor.
____
. {blank}
+
____
The Approved Methodology contains specific guidance on the scope of
evidence gathering necessary to provide reasonable assurance with
respect to the data the Project Proponent provides the Monitor.
____
. {blank}
+
____
The verification includes but is not limited to the following
categories:
____
[arabic]
.. {blank}
+
____
Project Plan - the verifier shall verify the information provided in the
Project Plan.
____
.. {blank}
+
____
Project Ownership and Rights
____
[arabic]
... {blank}
+
____
Verifier shall verify that the Project Proponent has legal rights to the
land defined in the project boundaries. If the Project Proponent is an
organization, the verifier shall also verify the documents provided to
Regen Registry have been signed by the organization’s representatives
without a reasonable doubt.
____
... {blank}
+
____
The verifier shall choose the appropriate level of Land Owner rights
verification from the list below, where the default shall be the least
strictest approach. Documentation verification levels, from strictest to
least:
____
[arabic]
.... {blank}
+
____
Evidence of land title or deed of ownership - official documentation of
Federal / State government.
____
.... {blank}
+
____
Rate payments, such as utility services provided by local jurisdictions
to the property and Project Proponent.
____
.... {blank}
+
____
Copies of email exchanges, letters, agreements or similar documentation
(or their extracts).
____
... {blank}
+
____
In the case the land is leased, the verifier shall also verify the lease
agreement between Project Proponent (or the entity/individual
represented) and Land Owner.
____
... {blank}
+
____
If the Project Proponent is representing the Land Owner, the verifier
shall verify the Deed of Representation between the Project Proponent
and the Land Owner.
____
.. {blank}
+
____
Data inputs provided by Project Proponent to the Monitor - as stipulated
by the Approved Methodology.
____
.. {blank}
+
____
The Monitor followed the procedures stipulated in the Approved
Methodology.
____
.. {blank}
+
____
Compliance
____
[arabic]
... {blank}
+
____
Compliance with Credit Class and Approved Methodology requirements:
____
[arabic]
.... {blank}
+
____
Project eligibility - see section above for full details. Including, but
not limited to:
____
[arabic]
..... {blank}
+
____
Ownership type - matches the type mentioned in Project Plan
____
..... {blank}
+
____
Project Activity falls within the defined accepted list of activities
____
..... {blank}
+
____
Project Area matches land tenure descriptions
____
..... {blank}
+
____
Adoption Date falls after the earliest accepted date and evidence is
provided to attest to that
____
.... {blank}
+
____
No double issuance - see Avoiding Double Counting section
____
... {blank}
+
____
Compliance with existing laws and regulations
____
.. {blank}
+
____
Leakage - verifying estimated leakage by Project Proponent is a
reasonable estimate (for example, uses regional default emission factors
or is in line with similar projects).
____

Table 1.0

[width="100%",cols="34%,66%",options="header",]
|===
|Verification Type |Applicable Evidence Category
|Project Registration |Project ownership and rights
| |Compliance
| |Monitoring and Co-Benefit data
|Credit Issuance |Monitoring and Co-Benefit data
| |Compliance
|Final Project Verification |Monitoring and Co-Benefit data
| |Compliance
|===

=== *Verification Report* 

[arabic, start=21]
. {blank}
+
____
Verifiers shall generate a report summarizing their findings, including
a verification rating from one of the following options:
____
[arabic]
.. {blank}
+
____
Acceptance - if all the corresponding requirements in the Evidence
Gathering section (10.4) have been satisfactorily met.
____
.. {blank}
+
____
Acceptance with Contingencies -
____
[arabic]
... {blank}
+
____
If there were any deviations from the Approved Methodology.
____
... {blank}
+
____
If data provided by the Project Proponent (e.g. in the Project Plan)
which is inconsequential to GHG estimation, could not be satisfactorily
verified.
____
.. {blank}
+
____
Rejection -
____
[arabic]
... {blank}
+
____
If project ownership could not be satisfactorily verified.
____
... {blank}
+
____
If the Monitor did not follow key Methodology guidelines (excluding
minor deviations).
____
... {blank}
+
____
If data provided by the Project Proponent for GHG estimation is
suspected to be fraudulent.
____
... {blank}
+
____
Lack of compliance with Project Eligibility, Double Counting
requirements, or existing laws/regulations.
____
. {blank}
+
____
In terms of data to sample, verifiers shall follow the guidance provided
in Table 1.0 per verification type.
____

=== *Verification Acceptance*

[arabic, start=23]
. {blank}
+
____
Regen Registry will review each verification report and proceed based on
its rating:
____
[arabic]
.. {blank}
+
____
Acceptance - Regen Registry will issue credits (if applicable) to the
Project Proponents per the monitoring outcome and Program Guide / Credit
Class stipulations.
____
.. {blank}
+
____
Acceptance with Contingencies -
____
[arabic]
... {blank}
+
____
the Project Proponent shall make the necessary corrections and
clarifications per the contingencies identified in the report. If
needed, the Verifier will resubmit their report after reviewing the
information provided by the Project Proponent.
____
... {blank}
+
____
Regen Registry will issue credits (if applicable) following the
Acceptance procedure above.
____
... {blank}
+
____
If the resubmitted verification report still retains the Acceptance with
Contingencies, Regen Registry will highlight this in the corresponding
MRV section.
____
.. {blank}
+
____
Rejection -
____
[arabic]
... {blank}
+
____
The project is put on hold until the issues identified are addressed
(see Project on Hold section).
____
... {blank}
+
____
The carbon stock level will revert to the last level that was recorded
and verified with the verification report with Acceptance or Acceptance
with Contingencies rating. If the project has already been issued
credits, then the Buffer Pool will be used to reconcile any gaps (see
Buffer Pool section).
____
. {blank}
+
____
Regen Registry will post all verification reports to Regen Registry.
____

=== *Verification Schedule*

[arabic, start=25]
. {blank}
+
____
The verification schedule will be optimized to limit the amount of
verifications needed and maximize the assurance level in credit
issuance:
____
[arabic]
.. {blank}
+
____
Project Registration - to be completed within six months after Project
Registration Date.
____
.. {blank}
+
____
Credit Issuance
____
[arabic]
... {blank}
+
____
Threshold verification - any issuance of GHG removal credit representing
more than 25K tons of CO2e/yr shall require a verification report prior
to issuance.
____
... {blank}
+
____
On-going verification - these are intended to provide assurances over
the maximum number of credits issued during the Crediting Term while at
the same time limiting the overall audit expenses. To that end, Project
Proponents shall select at which issuance event to perform this type of
verification such that each one covers at least two monitoring periods.
The verification shall be completed within three months of the last
monitoring round chosen. Note, there is no need for an additional round
of verification if a threshold based verification has occurred.
____
.. {blank}
+
____
Final Project Verification - to be completed at the end of the project;
must be a different verifier than the one used in prior verifications.
____

=== *Unscheduled Verification*

[arabic, start=26]
. {blank}
+
____
The following circumstances will warrant a potential additional
verification:
____
[arabic]
.. {blank}
+
____
A previous verification report with a Rejection or Acceptance with
Contingencies ranking.
____
.. {blank}
+
____
Significant variance (>25%) from benchmark carbon sequestration rates
for Project Activity.
____
.. {blank}
+
____
Compliance verifications - when Regen Registry has reasonable grounds to
suspect the Project Proponent has contravened, is contravening, or is
proposing to contravene with the rules and regulations.
____

=== *Verification Oversight*

[arabic, start=27]
. {blank}
+
____
Regen Registry reserves the right to conduct oversight activities of
verification performance participating verifiers. Oversight activities
are conducted to ensure an adequate level of quality control and are
intended to supplement accreditation body oversight and audit processes.
____

== Monitoring

____
Regen Registry requires monitoring to be conducted by an independent
Monitor chosen by the Project Proponent and approved by Regen Registry.

The Monitor shall follow the requirements in the Approved Methodology to
quantify the benefits and indicators defined in the respective Credit
Class.
____

=== *Definitions*

[arabic, start=28]
. {blank}
+
____
Monitoring [.mark]#means measurement of an ecological indicator(s),
following the guidelines of a given methodology. Measurements can use
various approaches, for instance remote sensing using satellite imagery
or estimation using biogeochemical methods.#
____
. {blank}
+
____
Baseline - a measurement of a certain ecological indicator tracked in a
given credit had the project not been implemented. A baseline can be
static, dynamic, project specific or based on performance standard (or a
combination of
those)footnote:[https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf[[.underline]#https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf#]].
____
. {blank}
+
____
Monitoring round - a scheduled time following the methodology guidelines
in which a Monitor performs the measurement or estimation of an
ecological indicator(s).
____

=== *Monitor Requirements*

[arabic, start=31]
. {blank}
+
____
The Project Proponent can choose a Monitor from either of the following
options:
____
[arabic]
.. {blank}
+
____
Regen Network monitoring services.
____
.. {blank}
+
____
Monitors that satisfy these minimum requirements:
____
[arabic]
... {blank}
+
____
Have sufficient proof of identity.
____
... {blank}
+
____
Obtain Errors & Omissions Insurance for at least $1 million.
____
... {blank}
+
____
Has demonstrated technical expertise in the methods specified in the
Approved Methodology, for example: satellite imagery and GIS analysis,
biogeochemical models (if applicable), statistical analysis, GHG
estimation, etc.
____
.. {blank}
+
____
Monitors must submit an application for consideration. A list of
approved Monitors will be made available on the Regen Registry website.
____
.. {blank}
+
____
Monitors must sign a statement confirming their lack of conflict of
interest with the Project Proponent. Regen Registry and the Project
Proponent must be satisfied that any potential for conflict of interest
can be mitigated. To limit the potential for conflict of interest, these
restrictions are put in place:
____
[arabic]
... {blank}
+
____
Monitors will not provide monitoring for any project in which:
____
[arabic]
.... {blank}
+
____
Any member of the monitoring team has a financial interest in the
project or the Project Proponent.
____
.... {blank}
+
____
The Monitor has played a role in implementing the Project Activity on
the ground.
____
... {blank}
+
____
The Monitor will disclose all relationships, such as familial or
fiduciary, within the past three years between the Monitor on the one
hand, and the project and Project Proponent on the other.
____
... {blank}
+
____
These requirements equally apply to Regen Network monitoring services.
____
.. {blank}
+
____
Regen Network Development acts as the first approved Monitor on Regen
Registry.
____

=== *Payment for Monitoring*

[arabic, start=32]
. {blank}
+
____
Project Proponent is responsible for engaging and paying for monitoring.
____

=== *Monitoring Procedure*

[arabic, start=33]
. {blank}
+
____
The Monitor shall gather all the monitoring data (if applicable)
provided by the Project Proponent using the respective Regen Registry
templates. If there is missing information, the Monitor will communicate
the gaps to the Project Proponent who in turn will resubmit the
monitoring data.
____
. {blank}
+
____
The Monitor shall gather all other sources of data specified in the
Approved Methodology necessary for the quantification process, for
example satellite imagery or metrics from scientific literature.
____
. {blank}
+
____
The Monitor shall use the appropriate tools and follow the procedures in
the Approved Methodology to quantify each ecological indicator.
____
. {blank}
+
____
The Monitor shall submit a monitoring report summarizing the
quantification results and including the number of credits the Project
Proponent is eligible for based on the definitions in the Approved
Methodology and the Credit Class. The Monitor shall apply any estimation
uncertainty deductions (if applicable per the Approved Methodology) to
the number of credits reported.
____

=== *Monitoring Procedure Deviations* 

[arabic, start=37]
. {blank}
+
____
Regen Registry will permit project-specific deviations from the Approved
Methodology where they do not negatively affect the conservativeness of
an Approved Methodology’s approach to the quantification of GHG
emissions reductions and removal enhancements.
____
. {blank}
+
____
Monitors shall submit any proposed project-specific deviation to Regen
Registry using the Deviation from Methodology
Templatefootnote:[https://drive.google.com/file/d/100bqmwJ-nIxK9VFXjq2ox3zvK5Son8XN/view?usp=sharing[[.underline]#Deviation
from Methodology Template#]]. Monitors must provide evidence that the
proposed deviation, such as a substitute calculation method for missing
data, meets the conservative standards of the methodology.
____
. {blank}
+
____
Regen Registry will review each such request, and if approved,
deviations can be applied to a specific project, but are not published
as modifications to the methodology.
____

=== *Monitoring Acceptance*

[arabic, start=40]
. {blank}
+
____
Regen Registry will review each monitoring report to verify it conforms
to the templates and the procedures specified in the Approved
Methodology. If corrections are needed, the Monitor shall resubmit the
monitoring report with the corrections.
____
. {blank}
+
____
Credit Issuance - If the monitoring report indicates the Project
Proponent is eligible for credits and no verification is needed (see the
Verification section requirements), Regen Registry will issue credits to
Project Proponent after the appropriate deductions as specified in the
Program Guide and Credit Class.
____
. {blank}
+
____
Regen Registry will make all monitoring reports publicly available.
____

=== *Monitoring Schedule*

[arabic, start=43]
. {blank}
+
____
The monitoring schedule will be dictated by the requirements in the
Approved Methodology and will include:
____
[arabic]
.. {blank}
+
____
Baseline measurement - performed upon project registration.
____
.. {blank}
+
____
On-going measurements - as needed per the Approved Methodology.
____
.. {blank}
+
____
Final Project Monitoring - to be completed at the end of the Crediting
Term.
____
.. {blank}
+
____
End of Permanence Monitoring - if applicable, a final monitoring round
will be completed at the end of the permanence period.
____

=== *Monitoring Oversight*

[arabic, start=44]
. {blank}
+
____
Regen Registry reserves the right to conduct oversight activities of
monitoring performance of participating verifiers. Oversight activities
are conducted to ensure an adequate level of quality control and are
intended to supplement accreditation body oversight and audit processes.
____

== Credit Classes

Regen Registry aims to democratize and invigorate the design of
ecosystem service credits. To that end we are separating out the typical
set of definitions that are part and parcel of most registry standards
and allow Credit Designers to modify and upgrade these as needed and
appropriate. These include:


- Credit definition
- Project eligibility requirements
- GHG accounting related requirements including permanence, leakage and
additionality.
- Verification requirements
- Reporting and compliance requirements

The Registry Program Guide and the Credit Class templates provide the
guidelines for creating new credits, thus enabling innovation while
maintaining a high standard of rigor.

While a subset of Credit Classes might be developed by RND, the
intention is to build a vibrant community of Credit Designers that will
take the lead going forward.

Regen Registry aims to create a broad set of Credit Classes that cover
different ecosystems, geographical regions and localities, and are
tailored for different stakeholders (e.g. smallholder farmers, corporate
farms, indigineous communities, conservation organizations, etc).

One of our key assumptions is that creating a one-size-fits-all solution
is suboptimal and does not tap into collective potential. Ecological
systems are inherently complex. Regenerative farming, grazing ,and
conservation are complex, nuanced, and locale specific. Similarly, the
needs and risk profile of credit buyers vary substantially depending on
the size of the company, its sector, climate goals, etc. As such, we
believe a successful solution needs to leverage commonalities and best
practices, while simultaneously allowing for flexibility in design.

=== New Credit Classes

The following process is applied to all new Credit Classes, whether
developed internally by RND or by external Credit Designers.

In such cases, Regen Registry coordinates a process of:

[loweralpha]
. Internal review
. Beta (optional)
. Technical review committee
. Public stakeholder consultation (optional)

Regen Registry administers the following process, at fees per the
current schedule.

. Concept note - the Credit Designer submits to Regen Registry a review
for a Credit Class concept note, included but not limited to the
following:

.. Market analysis demonstrating potential for GHG removal or improvement
in other relevant ecological indicators by the proposed activity.

.. An analysis of the ability and timing to scale impact given geographic,
regulatory or other pertinent considerations.

.. Sample project using (or planning to use) the proposed Credit Class
including an economic analysis demonstrating that the proposed activity
is viable under current market conditions.
+
Regen Registry will review the concept note and determine whether to
move forward with it.

. Credit Class draft - the Credit Designer submits the proposed new or
modified Credit Class to Regen Registry based on the appropriate
template. Regen Registry reviews the draft, asks for clarifications, and
points out corrections that are needed.

. Beta (optional) - once the necessary clarifications and corrections are
made, the Credit Designer can choose to move it to beta status. At this
point, a Project Proponent can apply for a project using the beta Credit
Class. Regen Registry encourages Credit Designers to collect feedback
from Project Proponents as they go through the beta process, in order to
ensure viability of the Credit Class. Feedback from the Project
Proponent on the proposed Credit Class will be documented by Regen
Registry and incorporated into the subsequent stages in the approval
process.

. Technical review committee - the revised Credit Class is provided to a
technical review committee that Regen Registry assembles consisting of
independent and impartial subject matter experts. Regen Registry
actively identifies and qualifies candidate committee members, and
publicly solicits applications from interested parties. Once the review
is complete, the committee lead compiles the comments and
recommendations from the committee, and prepares a summary report. Regen
Registry delivers to the Credit Designers the summary report, to which
they must respond by incorporating revisions and/or documenting
justifications for the proposed approach. Timing and cost of the
technical review committee depends on the complexity, scope, and quality
of the Credit Class and the availability of technical reviewers.

. Public consultation process (optional) - Regen Registry coordinates a
public consultation process. The Credit Class is posted publicly on the
Regen Registry website for a minimum of 30 days inviting public
comments. During this period, the Credit Designer may also choose to
conduct a webinar to present the draft Credit Class and solicit
additional comments. At the conclusion of the public comment period, the
comments are compiled into a report and sent to the Credit Designer, who
then has 30 days to respond to comments in writing and incorporate
relevant feedback to a revised version, which is then posted on the
Regen Registry website.

. Credit Class approval - once all required corrections have been made,
Regen Registry approves the new Credit Class and publishes it on its
website.

. Process documentation - Regen Registry documents the entire Credit Class
approval process including beta feedback, public comments and responses,
technical committee comments and responses, and the corresponding
versions of the Credit Class at each stage.

=== Modificationbs to Approved Credit Classes

Regen Registry may permit modifications to an existing approved Credit
Class where they maintain the guidelines stipulated in the Regen
Registry Program Guide. Credit Class modifications may be submitted for
review by Regen Registry, at fees per the current fee schedule. Regen
Registry will review the extent of the modification and determine what
steps in the approval process above need to be implemented.

=== Governance

Regen Registry will initially govern the process of adding new Credit
Classes per above process. In the future our aim is to move towards an
independent, decentralized governance of these methodologies by a broad
set of stakeholders, including subject matter experts, land stewards,
project developers, monitors, and verifiers.

== Methodologies

Regen Registry aims to establish a robust set of scientifically rigorous
methodologies, leveraging cutting edge technologies, and the latest
science. While a subset of these methodologies might be developed by
RND, the intention is to build a vibrant community of Methodology
Developers that will take the lead going forward.

=== New Methodologies

The following process is applied to all new methodologies, whether
developed internally by RND or by external Methodology Developers.

In such cases, Regen Registry coordinates a process of:

[loweralpha]
. Concept note and draft
. Beta (optional)
. Public stakeholder consultation
. Scientific peer review process.

Regen Registry administers this process, at fees per the current
schedule.

. Concept note - the Methodology Developer submits to Regen Registry for
review a methodology concept note, including but not limited to the
following:

  .. Market analysis demonstrating potential for GHG removal or improvement
in other relevant ecological indicators by the proposed activity.

  . Sample project using (or planning to use) the proposed methodology
including an economic analysis demonstrating that the proposed activity
is viable under current market conditions.

Regen Registry will review the concept note and determine whether to
move forward with it.

. Methodology draft - the Methodology Developer submits the proposed new
or modified methodology to Regen Registry following the appropriate
template. Regen Registry screens the methodology, asks for
clarifications and points out corrections that are needed.

. Beta (optional) - once the necessary clarifications and corrections are
made, the Methodology Developer can choose to move it to beta status. At
this point, a Project Proponent can apply for a project using the beta
methodology. Regen Registry encourages Methodology Developers to collect
feedback from Project Proponents as they go through the beta in order to
ensure viability of the methodology. Feedback from the Project Proponent
on the proposed methodology will be documented by Regen Registry and
incorporated into the public consultation process.

. Public consultation process - Regen Registry coordinates a public
consultation process. The methodology is posted publicly on the Regen
Registry website for a minimum of 30 days inviting public comments.
During this period, the Methodology Developer may also choose to conduct
a webinar to present the draft methodology and solicit additional
comments. At the conclusion of the public comment period, the comments
are compiled into a report and sent to the Methodology Developer, who
then has 30 days to respond to comments in writing and incorporate
relevant feedback to a revised version, which is then posted on the
Regen Registry website.

. Scientific peer review process - the revised methodology is provided to
a team of independent subject matter experts for a scientific peer
review process. Regen Registry may consult a technical committee in the
selection of impartial reviewers with the applicable subject matter
expertise. Regen Registry actively identifies and qualifies candidate
reviewers, and publicly solicits applications from interested parties.
Once the review is complete, the lead reviewer compiles comments and
recommendations from the peer review team, and prepares a summary
report. Regen Registry delivers to the Methodology Developer the peer
reviewed report, to which she must respond by incorporating revisions
and/or documenting justifications for the proposed approach. Generally,
several rounds of peer review are necessary. Timing and cost of peer
review depends on the complexity, scope, and quality of the methodology
and the availability of peer reviewers.

. Methodology approval - once all required corrections have been made,
Regen Registry approves the new methodology and publishes it on its
website.

. Process documentation - Regen Registry documents the entire methodology
approval process including beta feedback, public comments and responses,
peer review comments and responses, and the corresponding versions of
the methodology at each stage.

=== Modifications to Approved Methodologies

Regen Registry may permit modifications to an existing approved
methodology where they do not negatively affect the conservativeness of
the methodology’s approach to determining additionality and
quantification of GHG removals and co-benefits. Methodology
modifications may be submitted for review by Regen Registry, at fees per
the current fee schedule. Regen Registry will review the extent of the
modification and determine whether the internal review, public
consultation, and peer review process must be implemented. Modifications
to eligibility, applicability, Project Activities, and/or baseline
assumptions are likely to trigger the full process while minor
modifications to correct quantification errors or provide clarification
on monitoring requirements will not require the full process.

=== Regen Registry and Established Registries published methodologies

Current versions of methodologies for nature-based / AFOLU projects that
are approved by the Established Registries are generally approved for
use; however, Project Proponents implementing projects under these
methodologies must first go through the Regen Registry approval process
as described below.

=== Governance

Regen Registry will initially govern the process of adding new
methodologies per above process. Our aim is in the future to move
towards an independent, decentralized governance of these methodologies
by a broad set of stakeholders including subject matter experts, land
stewards, project developers, monitors, and verifiers.

== Co-Benefits 


=== Introduction

Co-benefits of climate change mitigation, as defined in the 4th
Assessment Report of the Intergovernmental Panel on Climate Change
(IPCC), are the positive benefits related to the reduction of GHG.
Examples of such climate mitigation policies include improved energy
efficiency of plants, renewable energy uptake and fuel switching, which
might enable a range of co-benefits, such as air-pollution impacts,
technological innovation, energy-supply security through increased
energy diversity, reduced fuel cost, and employment possibilities.

In the context of AFOLU projects, a variety of co-benefits are possible
including environmental, social, economic, indigineous rights, and many
more.

Interlinked with co-benefits is the shared blueprint the UN adopted in
2015 for peace and prosperity for people and the planet. At its heart
are the 17 Sustainable Development Goals
(SDGs)footnote:[https://sdgs.un.org/goals[[.underline]#https://sdgs.un.org/goals#]],
which are an urgent call for action by all countries in a global
partnership. They recognize that ending poverty and other deprivations
must go hand-in-hand with strategies that improve health and education,
reduce inequality, and spur economic growth – all while tackling climate
change and working to preserve our oceans and forests.

=== Credit Class requirements

Regen Registry is encouraging Credit Developers to include co-benefits
in all Credit Classes. This applies to both GHG removal credits and
other types of credits (e.g. biodiversity). In that sense we hold the
“co-benefit” term loosely in the sense that all benefits are important,
whether they are tied directly to climate change mitigation and GHG
removal or not.

Therefore, each Credit Class shall identify the applicable co-benefits
and how to measure and verify them. To that end, Regen Registry will
introduce in the future a framework and/or taxonomy to help Credit
Developers identify co-benefits and SDGs related to certain types of
projects, and stipulate how to measure and verify them. These
co-benefits and SDGs will be shown on Regen Registry to highlight the
broader impact of each project.
____

== Purchasing and selling credits


=== Account creation

Project Proponents (or sellers) and Buyers will create an account on
Regen Registry to which credits will be issued or transferred
respectively. The registration process might require an appropriate KYC
(Know Your Customer) verification depending on the nature of the asset
issued and corresponding regulations.

=== Selling credits

Credit holders - whether Project Proponents whom have been issued
credits or Buyers who had purchased tradable credits - have a few
options to sell their credits:

- Direct / offline sale - a seller can negotiate directly with a
prospective buyer and offer them the credits.

- Regen Registry brokerage services - a seller can choose to use Regen
Registry's brokerage services that will outreach to prospective buyers
and sell the credits at the price agreed upon with the Project
Proponent.

- Marketplace - a seller can offer the credits for sale on Regen Registry
online marketplace and select their price. The project credits can be
sold separately or as part of a portfolio of projects.

- Resell - this is a variant of the direct sale approach in which a seller
sells their credits to a third party, or a reseller, that in turn will
identify and sell the credits to a buyer(s).

- Exchange - in the future, a seller will be able to offer their credits
on an exchange facilitated by Regen Ledgerfootnote:[Exact timeline is
TBD; Q3, 2021 is the current target]

- 3rd party integrations - in the future, Regen Registry will establish
integrations with 3rd parties that offer GHG credits (offsets) for
instance to their respective client base.

- Auctions - in the future, Regen Registry may run a period auction as is
custom in some registries.

Note, these options will be updated on a regular basis and might change
from time to time. Further, as noted, not all of these options are
currently available.

=== Fee structure

The fee structure for the issuance and sale of credits depend on the
Credit Class, Methodology requirements and sales approach used. Regen
Registry will make the fee structure transparent on the website.

== Complaints and appeals

[arabic, start=2]
. {blank}
+
____
Complaints procedure
____

____
When a Project Proponent or other stakeholder objects to a decision made
by Regen Registry representatives or the application of the Regen
Registry program requirements, the following confidential complaint
procedure shall be followed:
____

* {blank}
+
____
Project Proponent or other stakeholder sends a written complaint via
email to
http://support-registry@regen.network[[.underline]#support-registry@regen.network#]
. The complaint must detail the following:
____
** {blank}
+
____
Description of the complaint with specific reference to the Program
Guide, Credit Class or Methodology requirements as applicable.
____
** {blank}
+
____
Supporting documentation provided for consideration in the complaint
resolution process.
____
** {blank}
+
____
Complainant name, contact details, and organization.
____

____
Regen Registry staff shall investigate the complaint. The staff member
assigned to handle the complaint shall not have been involved with the
issue that is the subject of the formal complaint. Regen Registry will
provide a written response, via email, to the complainant detailing the
decision on the matter.
____

[arabic]
. {blank}
+
____
Appeals procedure
____

____
In the event that a complaint remains unresolved after the conclusion of
the complaints procedure, the Project Proponent or stakeholder may
appeal any such decision or outcome reached. The following confidential
appeals procedure shall be followed:
____

* {blank}
+
____
Project Proponent or other stakeholder sends a written appeal via email
to
http://support-registry@regen.network[[.underline]#support-registry@regen.network#].
The appeal must detail the following:
____
** {blank}
+
____
Description of the complaint with specific reference to the Program
Guide, Credit Class or Methodology requirements as applicable;
____
** {blank}
+
____
Supporting documentation provided for consideration in the appeal
process, including previous communication on the complaint and all
relevant details of the previously implemented complaint procedure
____
** {blank}
+
____
Appellant name, contact details, and organization.
____
* {blank}
+
____
Regen Registry shall convene a committee to review and discuss the
matter. The committee will include a member of the RND board of
directors, a member of RND executive team, and an Regen Registry staff
member unrelated to the complaint, all of whom will have equal votes.
The committee may also include a technical and/or subject matter expert
or experts as necessary, who will not be able to vote. The committee
members selected will depend on the subject matter and nature of the
appeal.
____
* {blank}
+
____
The decision reached by the committee shall be communicated, via written
response, to the Project Proponent or stakeholder. Any decision reached
by the committee shall be final.
____

== Linkages to other registries

____
Regen Registry welcomes the opportunity to collaborate with other
reputable GHG (and other ecosystem service) programs, both voluntary and
regulated. The collaboration can manifest in different ways, including
but not limited to:
____

* {blank}
+
____
Digital MRV - providing low cost monitoring to project developers.
____
* {blank}
+
____
Marketplace and exchange - providing liquidity to sellers and buyers
along with built-in payments and billing infrastructure.
____
* {blank}
+
____
Marketing - showcasing the unique story of each project, highlighting
the land stewards behind it and the impact on the land and our
environment; providing buyers and policy makers with impact analytics on
a portfolio, regional, national and global level on key ecological
indicators.
____
* {blank}
+
____
Regen Ledger - providing a transparent and digital auditable tracking of
credit issuance and transfer, and monitoring and verification reports.
____

____
All of these integration points do not require any change to existing
infrastructure or procedures within these GHG programs. To learn more
please email
http://admin-registry@regen.network[[.underline]#admin-registry@regen.network#]
.

In the event, a Project Proponent wishes to transfer a project from
another GHG (or other ecosystem service) program, the project must
adhere to all the requirements in the Program Guide, and respective
Credit Class and Methodology. To avoid double issuance of GHG credits
(whether removals or emission reduction) see also the requirements in
the ‘Avoiding double counting’ section.
____

==  +

== References

The Program Guide is based on the foundation laid by the reference
standards and documentation below. These assisted RND to articulate our
own requirements and specifications for the MRV requirements, especially
as it relates to GHG guidelines that apply to AFOLU project-based
credits.

In particular the Program Guide has been informed by these
organizations:

* {blank}
+
____
American Carbon
Registryfootnote:[https://americancarbonregistry.org/[[.underline]#https://americancarbonregistry.org/#]]
____
* {blank}
+
____
The Australian Government’s Emission Reduction
Fundfootnote:[http://www.cleanenergyregulator.gov.au/ERF/[[.underline]#http://www.cleanenergyregulator.gov.au/ERF/#]]
____
* {blank}
+
____
Gold
Standardfootnote:[https://www.goldstandard.org/[[.underline]#https://www.goldstandard.org/#]]
____
* {blank}
+
____
Verra
(VCS)footnote:[https://verra.org/[[.underline]#https://verra.org/#]]
____
* {blank}
+
____
GHG
Protocolfootnote:[https://ghgprotocol.org/[[.underline]#https://ghgprotocol.org/#]]
____
* {blank}
+
____
Norifootnote:[https://nori.com/[[.underline]#https://nori.com/#]]
____

We salute and appreciate the effort of all these organizations!

This is a subset of the reference documentation used in writing this
guide:

[.underline]#American Carbon Registry#

* {blank}
+
____
ACR Standard v6.0
____

https://americancarbonregistry.org/carbon-accounting/standards-methodologies/american-carbon-registry-standard/acr-standard-v6_final_july-01-2019.pdf[[.underline]#https://americancarbonregistry.org/carbon-accounting/standards-methodologies/american-carbon-registry-standard/acr-standard-v6_final_july-01-2019.pdf#]

* {blank}
+
____
ACR Risk Tool v1.0
____

____
https://americancarbonregistry.org/carbon-accounting/guidance-tools-templates/acr-risk-tool-v1-0.pdf[[.underline]#https://americancarbonregistry.org/carbon-accounting/guidance-tools-templates/acr-risk-tool-v1-0.pdf#]
____

[.underline]#The Australian Government’s Emission Reduction Fund#

* {blank}
+
____
Carbon Credits (Carbon Farming Initiative - Measurement of Soil Carbon
Sequestration in Agricultural Systems) Methodology Determination 2018
____

https://www.legislation.gov.au/Details/F2018L00089[[.underline]#https://www.legislation.gov.au/Details/F2018L00089#]

* {blank}
+
____
The Supplement To the Carbon Credits (Carbon Farming Initiative -
Measurement of Soil Carbon Sequestration in Agricultural Systems)
Methodology Determination 2018
____

____
https://www.environment.gov.au/system/files/consultations/072b4825-ec0f-49d9-991e-42dfa1fbeae3/files/supplement-soil-carbon-agricultural-systems.pdf[[.underline]#https://www.environment.gov.au/system/files/consultations/072b4825-ec0f-49d9-991e-42dfa1fbeae3/files/supplement-soil-carbon-agricultural-systems.pdf#]
____

[.underline]#Verra#

* {blank}
+
____
VCS Program Guide v4.0
____

https://verra.org/wp-content/uploads/2019/09/VCS_Program_Guide_v4.0.pdf[[.underline]#https://verra.org/wp-content/uploads/2019/09/VCS_Program_Guide_v4.0.pdf#]

[.underline]#GHG Protocol#

* {blank}
+
____
GHG Project Protocol
____

____
https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf[[.underline]#https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf#]
____

* {blank}
+
____
https://ghgprotocol.org/sites/default/files/standards_supporting/LULUCF%20Guidance_1.pdf[Land
Use&#44; Land-Use Change&#44; and Forestry (LULUCF) Guidance for GHG
Project Accounting
[.underline]#https://ghgprotocol.org/sites/default/files/standards_supporting/LULUCF%20Guidance_1.pdf#]
____

[.underline]#Nori#

* {blank}
+
____
How it Works
____

____
https://nori.com/resources/how-nori-works[[.underline]#https://nori.com/resources/how-nori-works#]
____

== 
