= Regen Registry Program Guide
Ron Steinherz
v1.0, December 18, 2020
:description: 
:toc:

[discrete]
== Disclaimer

This document has been prepared for informational and procedural
purposes only. Its contents are not intended to constitute legal advice.
Regen Network Development, Inc (RND) maintains the right to amend or
depart from any procedure or practice referred to in this guideline as
deemed necessary.


== Definitions

[horizontal]

Credit Designer::

an individual or organization that is developing a new
Credit Class or updating an existing one.


Methodology Developer::

an individual or organization that is developing
a new Methodology or updating an existing one.

Monitor::

an individual or organization that is contracted to measure
the benefits / indicators defined in a given Credit Class based on the
stipulations in the Approved Methodology.

Verifier::

an individual or organization that is contracted to execute
the verification requirements stipulated in a given Credit Class.

Broker::

an individual or organization that is offering brokerage
services to credit owners.

Project Proponent::

the project developer or land steward that is
applying to register a project on the registry.

Buyer::

an individual or organization that is purchasing credits from
the registry.

Validator::

independent operators of the nodes that secure Regen Ledger.

Project Developer::

the individual or organization that is in charge of
managing the project and is the main point of contact with Regen
Registry. The Project Developer can be the land steward or a third
party.

Land Steward::

the individual or organization that is performing the
work on the ground. This can be a farmer, rancher, conservationist,
forester, fisherman, etc.

Land Owner::

the individual or organization that holds title to the land
where the project is occurring in. This can be the Land Steward or a
third party that rents the land to the Land Steward.

Project Registration Date::

the official date when a project commences.

Approved Methodology::

the corresponding approved methodology(s) for a
given Credit Class.

Credit Class::

similar to a standard in other registries, it defines the
structure, procedures and requirements related to a certain credit type.

Project Plan::

the template that each project proponent fills out in
order to register a project on the registry.

Co-Benefit::

the Intergovernmental Panel on Climate Change
(IPCC) defines co-benefits of climate change mitigation as the positive
benefits related to the reduction of greenhouse gases. We define it more
broadly as# a benefit that is achieved along with the main indicator
tracked and promoted in a given credit - which need not be a reduction
of GHG. For example, a biodiversity credit might mainly promote the
protection of a certain species and at the same time offer co-benefits,
such as protection of water resources.

Baseline::

an estimate of the measurement of a certain benefit /
indicator tracked in a given credit had the project not been
implemented. A baseline can be static, dynamic, project specific or
based on performance standard (or a combination of
those)footnote:[https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf[https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf]].

Verification::

a systematic, independent, and documented assessment by a
qualified and impartial third party of the benefits' assertions for a
specific reporting period.

Supplement::

an appendix to the Credit Class or Approved Methodology
that contains stipulations related to a specific geographic locale or a
specific case.

Crediting Term::

is the finite length of time for which a Project Plan
is effective, and during which a project can generate credits.

Project Activity::

the applied management or conservation practice that
a project proponent is undertaking in order to improve the benefits
tracked in a given Credit Class.

Project Initial Monitoring Date::

the date when the baseline measurement
was performed

Project Page::

the dedicated web page for a given project on the
registry. It provides an overview of the project, the activities taken
place, timeline, images, maps, documentation, and more.

Permanence Reversal Buffer::

a dedicated buffer account that is
allocated a percentage of credits from each issuance in order to
mitigate permanence related reversal risk, i.e. GHG removal reversal
that has occurred over the permanence period of the project.

Approved Activities::

the set of land management or conservation
activities that are eligible activities for a given Credit Class.

Established Registries::

other reputable registries in the carbon market
that Regen Registry recognizes and accepts for certain purposes, such as
onboarding verifiers. These registries are:
+
[loweralpha]
. Verrafootnote:[https://verra.org/[https://verra.org/]] -
VCS Program , CCB Program, Jurisdictional & Nested REDD+ , SD Vista
. Gold Standardfootnote:[https://registry.goldstandard.org/[https://registry.goldstandard.org/]]
. American Carbon Registryfootnote:[https://americancarbonregistry.org/[https://americancarbonregistry.org/]]
. Climate Action Reservefootnote:[http://www.climateactionreserve.org/[http://www.climateactionreserve.org/]]
. CDMfootnote:[https://cdm.unfccc.int/index.html[https://cdm.unfccc.int/index.html]]
. Australian Emission Reduction Fund - Carbon Farming Initiativefootnote:[http://cleanenergyregulator.gov.au/ERF/project-and-contracts-registers/project-register[http://cleanenergyregulator.gov.au/ERF/project-and-contracts-registers/project-register]]


== Acronyms


[horizontal]
GHG:: Greenhouse Gases
IPCC:: Intergovernmental Panel on Climate Change (IPCC) is an
intergovernmental body of the United Nations that is dedicated to
providing the world with objective, scientific information relevant to
understanding the scientific basis of the risk of human-induced climate
change.
AFOLU:: Agriculture, Forestry and Other Land Use; a category of carbon
credit projects that related to agriculture, forestry, and other land
uses (e.g. conservation).
RND:: Regen Network Development, Inc , the entity developing and
operating Regen Registry. Also referred to in this document as Regen
Network.
SDG:: the United Nations' Sustainable Development Goals.
GIS:: Geographic information system is a conceptualized
framework that provides the ability to capture and analyze
https://en.wikipedia.org/wiki/Spatial_analysis[spatial] and
https://en.wikipedia.org/wiki/Geographic_data_and_information[geographic
data].

:sectnums: 
:sectnumlevels: 3

== Introduction

Every day, business is done while neglecting some of our most important
partners: Farmers and the Earth. The result are destructive global
consequences like climate change, desertification, and resource
depletion that affect nearly every aspect of human life. The United
Nations FAO estimates 33% of the Earth's soils are already
degraded and over 90% could become degraded by
2050footnote:[FAO and ITPS, 2015; IPBES, 2018].

The price tag to 'fix' these problems is estimated to be in the
trillions, paralyzing global efforts to quickly address climate change.
There may be nothing of more critical importance today than the
regeneration of the world's ecosystems.

Farmers, the stewards of our global landscapes, offer one of the most
powerful pathways for reversing climate change and unlocking a massive
untapped market in the world: the services and products generated by
Earth's ecosystems. Regen Registry coupled with Regen Ledger, an
ecological blockchain-based ledger, create a new platform for farmers to
monetize their ecological data while receiving rewards for sustainable
practices. By improving the understanding of the state of our land,
oceans, and watersheds and enabling rewards for verified positive
changes, Regen Network catalyzes the regeneration of our ecosystems.

Regen Network was launched in Q2, 2018 and is headquartered in Great
Barrington, Massachusetts.

== Overview

The Program Guide details the general requirements and specifications
for the quantification, monitoring, reporting and verification (MRV),
project registration, and issuance of credits on Regen Registry. The
common characteristic of all Regen Registry credits is that they are all
nature-based solutions, and each can provide one or more ecosystem
services, including GHG emissions reductions and removals,
biodiversity/habitat protection, improvement in water quality, and
morefootnote:[Note, the taxonomy of carbon markets and climate
mitigation varies from ecosystem services].

The Program Guide establishes the programmatic structure of Regen
Registry, including credit classes and methodologies, the project
registration process, project eligibility, and the issuance of tradable
environmental assets to projects. This guide is intended to be used by
Project Proponents, buyers, Monitors, Verifiers, and all other
stakeholders.

Regen Registry aims to maximize flexibility and usability for Project
Proponents while maintaining the environmental integrity and scientific
rigor necessary to ensure that projects developed against its credit
classes and methodologies are of the highest quality.

Project Proponents developing a project for registration on Regen
Registry shall follow this Program Guide and must apply a Regen Registry
approved credit class and methodology.

Project Proponents and other interested stakeholders should refer to the
Regen Registry website for the latest version of the Program Guide,
methodologies, document templates, and other guidance. Regen Registry
will inform Project Proponents with active projects directly to avoid
any potential disruptions.

== Basics

=== Description

Regen Registry is an open source ecosystem services registry in which
Project Proponents can register projects, apply for credits, and
transfer and sell credits to buyers. Buyers can resell or retire credits
(in the case of carbon credits). Each credit vintage issued has a unique
ID, is project-based, is geospatially tagged and independently
verifiedfootnote:[If an independent verification is required by the
respective Credit Class].

Regen Registry aims to provide an open source, vertically integrated
solution that provides:

[loweralpha]
. **Digital MRV** - software infrastructure that provides monitoring
tools - through in-house remote sensing and interoperability with 3rd
party tools - that streamline the cost and issuance of credits.
. **Marketing Platform** - showcases the unique story of each
project, highlighting the land stewards, the impact on the land and
environment; provides buyers and policy makers with impact analytics on
a portfolio (regional, national, and global) of key ecological
indicators.
. **Marketplace and exchange (trading platform)** - sellers offer
their credits for sale; buyers purchase from one or multiple projects
and build a portfolio; the system provides a clearing [.mark]#and
settlement infrastructure including# payments and billing.
. **Regen Ledger** - a custom-built ecological ledger using
blockchain technology where credits are issued and transferred, and
monitoring and verification claims are recorded as immutable records.

Each layer offered within the Regen Registry is standalone and Project
Proponents can choose which ones to use. For example, a Project
Proponent can choose to perform the monitoring in-house, based on the
methodology guidelines, rather than use a Monitor that leverages our
software stack. That said, integrated use of all layers will enable
significant advantages in ease-of-use, effectiveness, and cost
efficiency.

=== Objectives 

Regen Registry's objectives are to:

- Encourage nature-based solutions. For example, solutions based on
regenerative agriculture, conservation, and best management practices,
as a strategy to mitigate (by removing/reducing GHG emissions) and/or
adapt to climate change.

- Provide guidance for, and promote, scientifically rigorous methodologies
and credit classes to foster high quality ecological assets.

- Create an open-source infrastructure that allows cost-effective and
rigorous MRV implementation, issues and tracks credits while avoiding
double counting, and provides payments, billing, and marketing
functionality.

- Support best practices in project-level GHG accounting and ecosystem
services.

- Commercialize innovative types of credits bundled with valuable
co-benefits and ecosystem services.

- Provide an environment to develop new types of ecological assets that
will inform voluntary and regulated markets.

- Incorporate cutting-edge technologies, such as IoT sensors, satellite
remote sensing, and digital signatures, in the use of project monitoring
and verification.

- Enhance public confidence in market-based action for GHG removal and
ecosystems' regeneration.

- Support interoperability between climate markets emerging from the
UNFCCC's Paris Agreement and global NDC commitments.

=== Scope

==== Geography

. Regen Registry accepts projects from locations worldwide, provided they conform to an approved credit class and its respective methodology.

==== Project Types

Regen Registry encourages and accepts a broad variety of nature-based
projects that promote climate mitigation, adaptation, and regeneration
of ecosystems, such as:

- *Agricultural projects* - examples include the adoption of cropland
practices that sequester carbon, such as reduced tillage or planting
cover crops, or pastureland / rangeland practices, such as rotational
grazing.

- *Water management projects* - examples include the installation of swales
that reduce nutrient runoff.

- *Forestry projects* - examples include afforestation, reforestation, and
agroforestry projects.

==== Users

The following depicts the main users of Regen Registry:

- *Credit Designer* - an individual or organization that is developing a new
Credit Class or updating an existing Credit Class.

- *Methodology Developer* - an individual or organization that is developing
a new Methodology or updating an existing Methodology.

- *Monitor* - an individual or organization that is contracted to measure
the benefits / indicators defined in a given Credit Class, based on the
requirements of an Approved Methodology.

- *Verifier* - an individual or organization that is contracted to execute
the verification requirements of a given Credit Class.

- *Broker* - an individual or organization that offers brokerage services to
credit owners.

- *Project Proponent* - the project developer or land steward that applies
to register a project on the registry.

- *Project Developer* - the individual or organization that manages a
registered project and is the main point of contact with Regen Registry.
The Project Developer can be the land steward or a third-party.

- *Land Steward* - the individual or organization that performs the work
on-the-ground. This can be a farmer, rancher, conservationist, forester,
fisherman, etc.

- *Land Owner* - the individual or organization that holds title to the land
where the project is occurring. This can be the Land Steward or a
third-party that rents the land to the Land Steward.

- *Buyer* - an individual or organization that is purchasing credits from
the Regen Registry.

==== Adoption and Revisions

Regen Registry aims to update the Program Guide on a yearly basis in
order to accommodate changes in science and technology which inform
new/upgraded methodologies, and changes in climate markets including GHG
accounting best practices, legislative and/or regulatory requirements.

On a project level and in certain circumstances, Regen Registry may
require all projects, including those monitored and verified under a
previous version of the Program Guide, to implement a policy or process
revision (e.g., updated administrative reporting procedures) detailed in
a subsequent version of the Program Guide.

New/subsequent versions of the Program Guide will be posted for public
comment for 30 days prior to adoption. Regen Registry will prepare
responses to submitted comments and post the comments and responses
along with the new version of the Program Guide.

==== Data Submission and Record-Keeping

Where appropriate, Regen Registry will provide templates for Project
Proponents to collect and submit data for project registration,
monitoring, and verification. These templates will be updated as needed.
In the future, templates will migrate to online/digital interfaces,
including digital signatures that simplify data collection and
processing, enable interoperability with 3rd party tools, and provide a
digital audit trail.

==== Conflict of Interest

Regen Registry requires that third-party Monitors and Verifiers sign a
Conflict of Interest agreement.

=== Guiding Principles 

==== Accuracy 

The Project Proponent shall reduce, as far as is practical,
uncertainties related to the quantification of GHG removals and/or any
other applicable ecological indicator, such as species habitat, tree
coverage, etc.

Methodologies submitted for Regen Registry approval shall include
methods for estimating the uncertainty for each indicator. If
the width of the 90% confidence interval exceeds 20%, an appropriate
confidence deduction shall be applied.

The use of models, such as biogeochemical models, must include an
estimate of structural uncertainty related to the inadequacy of the
model, model bias, and model discrepancy. Monitors shall quantify these
using the best available science, Monte Carlo analyses, uncertainty
estimates from peer reviewed literature, and/or consulting model experts
who have either developed or worked directly with the model in an
academic setting.

==== Comparability

Methodologies approved on Regen Registry shall rely on comparable
peer-reviewed studies as best as possible.

Further, Regen Registry is building infrastructure for automated
monitoring processes that will enable, once monitoring has been
performed for a given project, to have an independent party run that
same monitoring process again, at will, in order to compare the results.
We believe this will provide a new level of transparency and assurance
to monitoring processes.

==== Continuously and Frequently Upgraded

Regen Registry encourages updates of the Program Guide, Credit Classes,
and Methodologies in order to incorporate the latest scientific
knowledge, technologies, and tools, such as IoT and remote sensing.

==== Transparency

Regen Registry is built to provide stakeholders, including Project
Proponents, Buyers, scientists, and market experts, with a high level of
transparency. We achieve this by:

- Credit Classes and Methodologies are publicly available and receive
public comment. We also encourage engaging a broad set of subject matter
experts during the design process.

- All pertinent project data is publicly available, including the Project
Plan, monitoring reports, credit issuance certification, and
verification reports.

-  Regen Ledger will provide an immutable record and digital audit trail of
monitoring and verification outcomes, and credit issuance and sales.

See also the GHG Accounting and Policies section.

==== Collaboration

Regen Registry believes deeply in collaboration. We are convening a
broad set of independent parties to participate in:

- *Methodology development and Credit Class design* - scientists, economists
and subject matter experts are invited to create new, cutting-edge
ecological assets, to provide feedback, and to govern the library of
methodologies and credit classes.

- *Monitoring and verification* - remote sensing companies, experts, IoT
providers, surveying tools, etc. are invited to provide their monitoring
services to streamline the costs of MRV while maintaining scientific
rigor.

- *Regen Registry platform and Regen Ledger development* - software
developers who are eager to mitigate climate change are welcome to
contribute to these open source projects.

To that end, RND is also an active member
OpenTEAMfootnote:[https://openteam.community/], or Open Technology
Ecosystem for Agricultural Management, a farmer-driven, interoperable
platform to provide farmers around the world with the best possible
knowledge to improve soil health. We are currently collaborating with
OpenTEAM members in creating digital, open source, and standardized data
collection from the field and from MRV providers.

==== Practicality

Regen Registry aims to balance the time and cost required by Project
Proponents to collect data for monitoring, verification and reporting
and the need for assurances from Credit Buyers. To that end, Regen
Registry encourages a tiered approach to methodology development that
will provide different levels of assurances to cater to different needs
of Credit Buyers.

==== Security

RND will conduct security audits of its software, including Regen Ledger
and Regen Registry, to ensure the data integrity and fidelity of credit
ownership and the underlying MRV data.

==== Open Source and Open Data

Following the collaboration principle above, RND is a strong proponent
of open-source software and open data. We firmly believe that in order
to achieve the best results, provide transparency, ensure fair
governance, and invite collaboration from multiple stakeholders, we need
to develop open source software and share our research data openly. Our
software code repositories are available on
GitHubfootnote:[https://github.com/regen-network/[https://github.com/regen-network/]]

==== User-Centric Design

Relative to their potential, Agriculture, Forestry and Other Land Use
(AFOLU) carbon credits have seen limited adoption in regulatory and
voluntary markets. Historically, the supply of these credits has been
limited because credit design has not incorporated enough feedback from
land stewards, resulting in credit requirements that were complicated,
expensive and/or time consuming. Regen Registry follows a user centric
design of credit classes and methodologies with input not only from
buyers but also land stewards and project developers.

== Governance

Regen Registry is built on the principles of openness, collaboration,
accountability, user centric design, transparency, responsiveness, and
participation. This is applied to Credit Class and Methodology design,
provision of monitoring and verification services, integration with
other registries, and with 3rd-party service providers.

Regen Registry relies on a software implementation that includes two
layers:

[loweralpha]
. Regen Registry platform - a centralized software layer that
provides user accounts, project pages, administrative functions and

. Regen Ledgerfootnote:[Integration of Regen Registry and Regen Ledger is
targeted for Q2 2021] - a decentralized software layer that is used to
issue, transfer, and retire credits and tracks all pertinent monitoring,
reporting and verification (MRV) information as immutable records.

Regen Registry is operated by Regen Network Development, Inc (RND), a
private for-profit company. Regen Ledger is a public decentralized
ledger that is not owned by a single entity (including RND) and is a
Digital
Commonsfootnote:[https://en.wikipedia.org/wiki/Digital_commons_(economics)[https://en.wikipedia.org/wiki/Digital_commons_(economics)]]
that is operated by a network of independent stakeholders called
Validators that are incentivized to maintain the integrity of the
underlying ecological data and credits tracked on the ledger. Regen
Network believes this is the best way to maintain long term data
integrity, auditability, transparency, and viability, and enables a just
allocation of resources and sustained regeneration of ecological
ecosystems (see blog
postfootnote:[https://medium.com/regen-network/community-stake-governance-model-b949bcb1eca3[https://medium.com/regen-network/community-stake-governance-model-b949bcb1eca3]]
for more details).

Regen Registry is committed to fully comply with all relevant U.S.
Commodity Futures Trading Commission (CFTC) and the U.S. Securities and
Exchange Commission (SEC) standards and regulations.

In the event that RND dissolves, the Regen Registry's contractual
agreements bind both project developers and buyers to uphold any
outstanding contractual commitments as if the two slides are direct
parties to the contracts.

== Project eligiblity

=== Ecosystem Type 

Each Credit Class and Methodology shall stipulate the Ecosystem Type
based on RND
taxonomyfootnote:[https://docs.google.com/spreadsheets/d/1_i9aKoC-sgaRgNAIa8QL4P-ZgmmamdPjsihEHEzpCys/edit?usp=sharing[RND
Taxonomy Document]]. In the event there is no matching definition in
the taxonomy, the Credit Designer or Methodology Developer will propose
an addition to the taxonomy.

=== Ecosystem Service Classification

Each Credit Class and Methodology shall stipulate the Ecosystem Service
based on RND
taxonomyfootnote:[https://docs.google.com/spreadsheets/d/1_i9aKoC-sgaRgNAIa8QL4P-ZgmmamdPjsihEHEzpCys/edit?usp=sharing[RND
Taxonomy Document]]. In the event there is no matching definition in
the taxonomy, the Credit Designer or Methodology Developer will propose
an addition to the taxonomy.

=== Land Ownership Type

Each Credit Class shall stipulate the land ownership type accepted, for
example:

- Private
- Public
- Tribal

Or combination of the above.

=== Adoption Date

The Adoption Date is the date on which the Project Proponent began to
apply the Project Activity intended to increase a certain ecological
outcome (e.g. carbon stock) relative to the baseline measurement.

Each Credit Class shall define the earliest Adoption Date accepted for
that credit, but no earlier than 10 years prior to Project Registration
Date.

The Project Proponent must provide evidence to that effect.

=== Crediting Term

Crediting Term is the finite length of time for which a Project Plan is
valid, and during which a project can generate credits.

Each Credit Class shall define the corresponding Crediting Term(s)
available for that credit.

=== GHG Removal/Emission Reduction Requirements

Credit Classes that include GHG removals shall include these related
requirements:

==== Real

A real offset is the result of a Project Activity that yields
quantifiable and verifiable GHG removals as stipulated in the Approved
Methodology.

==== Measurable

Each credit represents one ton CO~2~e (1t CO~2~e) that has been removed
(or avoided) from the atmosphere.

==== No Double Counting

Regen Registry does not allow double issuing and selling of credits for
the same project area and/or temporal boundary. See also 'Registration
on other registries' section.

=== Land Tenure

. Land tenure is a legal term representing rights and interests in project
lands.

. Project Proponent shall own, have control over, or document effective
control over the GHG sources/sinks from which the removals originate.

. Project Proponent shall provide documentation and/or attestation of land
tenure.

. In the case of leased land, the landowner shall agree to all contractual
obligations taken by the Project Proponent, and the project Proponent
shall provide documentation and/or attestation of title agreement to
credits.

. Regen Registry may require a legal review by an expert in local law.

=== Regulatory Compliance

. Projects must maintain material regulatory compliance, that is, adherent
to all laws, regulations, and other legally binding mandates directly
related to Project Activities.

. Project Proponent is required to provide a regulatory compliance
attestation for each verification. This attestation must disclose all
violations or other instances of non-compliance with laws, regulations,
or other legally binding mandates directly related to Project
Activities.

. Regen Registry retains discretion to decide on a case-by-case basis
whether a violation requires cancelling the project or putting it on
hold until the issue is addressed.

=== Project Area

. The Project Area may only include land meeting the following
requirements:
    - the land was not converted from forest land, wetlands or any other
    natural ecosystem (see rnd taxonomy document for definitions) in the 10
    year period prior to the Project's Adoption Date.

. The Project Area may include portions of land which are not eligible
land, only if they are excluded from any GHG or co-benefit estimation.
Those areas will be clearly demarcated in the Project Plan.

=== Registration on other Registries

. Project Proponent is required to state if they plan to apply in the
future, or have applied for and been listed, registered, and/or been
issued GHG emission reduction or removal credits, biodiversity credits
or any other ecological credit through any other GHG emissions program,
biodiversity program or any other certification program.

. Project Proponent will include detailed information on any credit
issuance (volume, vintage, status), and information on any rejections of
the project application on other registries.

. Regen Registry will review the information provided by Project Proponent
and approve or reject concurrent registration with another registry(s).
Regen Registry will permit concurrent project registration only if the
following conditions are met:

- No double issuance - credits issued for the same unique emissions
reductions (project boundary and vintage) do not reside concurrently on
more than one registry.

- No double sale - once any credits have been sold on another registry,
the Project Proponent will be required to cancel that project in order
to register on Regen Registry.

Note, these conditions hold, not only during project registration but
throughout the lifetime of the project. That is, Project Proponent with
an existing project on Regen Registry shall follow the same procedure
above if planning to register on another registry concurrently.

See Avoiding Double Counting section for more details.

== Project Rules and Regulations

=== Approved Methodology

Each Credit Class shall define the Approved Methodology(s) which the
credit relies upon.

=== Project Plan

The Project Plan describes the Project Activity, addresses eligibility
requirements, establishes project boundaries, and more. The Project
Proponent shall fill out the Project Plan
templatefootnote:[https://drive.google.com/file/d/1q6-26M-ROqKpfbkZf8YSDG2j2vawiVun/view?usp=sharing[Regen
Registry Project Plan]] and submit for review by Regen Registry.

=== Project Lifecycle

This is a general outline of the project stages:

. Account Creation - Project Proponent provides contact information and
creates an account on Regen Registry.

. Project Creation - Project Proponent creates a project, applies for a
credit, completes the Project Plan, and signs the corresponding legal
agreements.

. Preliminary Review - Regen Registry reviews the submission for
completeness and compatibility with the Credit Class and Approved
Methodology, and requests additional information as needed.

. Project Registration - If everything is in order, the project is
approved, the contract is signed between the Project Proponent and Regen
Registry.

. Baseline Measurement - Project Proponent engages with Monitor and
provides the project information as defined in the Approved Methodology.
The Monitor follows the guidelines in the Approved Methodology and
generates a baseline measurement of the ecological indicators and
benefit assessment assigned to the Credit Class. The Baseline Monitoring
Report is submitted to Regen Registry. If the report is approved, it is
made publicly available on Regen Registry.

. Verification - Per the verification schedule defined in the Credit
Class, the Project Proponent engages with an independent, approved
Verifier to verify the inputs provided by the Project Proponent and the
baseline and monitoring reports submitted by the Monitor follow the
specification of the Approved Methodology. Fees for verification are
determined by the Project Proponent and Verifier. The Verifier submits
to Regen Registry a verified Project Plan, verified monitoring
report(s), and verification report with verification rating (see
Verification section for further details).

. Verification Acceptance - Based on the verification report rating, Regen
Registry issues credits to the Project Proponent. The verification
report is made publicly available on Regen Registry.

. Subsequent Monitoring and Verification rounds - Following the guidelines
in the Approved Methodology and Credit Class, subsequent monitoring and
verification rounds are performed, and the above steps repeat for each
credit vintage issuance.

. Issuance - Regen Registry issues to the Project Proponent’s account
credits for the relevant reporting period, in the amount listed in the
monitoring report.

. Transfer or Retire - At the Project Proponent’s discretion, they can
sell or retire the credits.

. Final Project Verification - At the end of the Crediting Term, the
Project Proponent will engage in a final project verification. The
report will be made public on Regen Registry.

. Project Renewal (optional) - After the final project verification, the
Project Proponent can elect to renew the project. The duration for
renewal is defined by each Credit Class.

GHG removal projects’ specific adaptations:

[arabic, start=13]
. Credit issuance - With each issuance, a percentage of credits, as
defined in the Credit Class, is deposited into the Buffer Pool.

. Buffer pool reconciliation - Based on the end-of-project carbon stock
estimation, Regen Registry will retire or transfer credits from the
Buffer Pool. See the Buffer Pool section.

. Permanence Monitoring and Verification - At the end of the permanence
period, the Project Proponent will conduct a permanence monitoring and
verification round (desk review) in order to verify retention of GHG
removed during the project.

=== Project Ownership

Project Proponent shall stipulate the ownership of credits issued to the
project. Regen Registry supports fractional ownership of the credits
allocated to a project in a given issuance event, therefore credits can
be split between Land Stewards, Land Owners, Project Developers, and
Buyers.

=== Project Registration Date

. The Project Registration Date is the date the Project has been approved
by Regen Registry. The Crediting Term officially begins on this date.

. If an Adoption Date precedes the Project Registration Date, the
Crediting Term will commence at the Project Initial Monitoring Date as
defined by the Approved Methodology.

=== Project Renewal

. At the end of the project, the Project Proponent can elect to renew the
project. The Project Proponent may do so by:

.. Choosing from these renewal period options: 5, 10, 15 or 20 years.
.. Submitting an updated Project Plan in compliance with up-to-date Credit
Class and Approved Methodology.

. The final project monitoring and verification round of carbon stock
and/or other ecological indicator estimates will be automatically used
as the renewal up-to-date baseline.

. Project Proponents may renew a project multiple times. Regen Registry
does not limit the number of periods of renewal that are allowed for a
given project renewals.

=== Project Monitoring Reports

. Project Monitoring Reports shall be completed for each monitoring period
following the template for Project Monitoring Report. The Monitor shall
submit the report to Regen Registry including any corrections/revisions
identified by the verifier (if applicable).

. The Monitoring Report shall describe the current status of project
operation, and include the data monitored, the monitoring plan, the
calculated emission reductions and ecological indicators for the
reporting period stated in the Credit Class and following the guidelines
in the Approved Methodology.

=== Project Termination 

==== End of Crediting Term 


. At the end of the Crediting Term, the Project Proponent will engage in a
final project verification. The report will be made public on Regen
Registry.

. The Project Proponent has the choice to renew the project (renewal
duration stipulated in Credit class).

. In the case of a GHG removal credit, based on the end of project carbon
stock estimation, Regen Registry will retire or issue credits from the
Buffer Pool. See the Buffer Pool section for more details.

====  Premature Project Termination 

. Prior to credit sales transactions (i.e. sold, transferred, or retired),
a Project Proponent can decide to end the project prematurely with no
penalties.

. Regen Registry fees will still apply, along with any outstanding
obligations between Project Proponent and 3rd parties, such as Verifiers
and/or Monitors.

==== In the case of a GHG removal credit

. Before credit sales transactions, project credits in the Project
Proponent's account will be cancelled including the respective Buffer
Pool and Permanence Reversal Buffer allocations.

. After credit sales transactions, the Project Proponent:

.. Shall engage with a final monitoring and verification round to calculate
the carbon stock levels and determine Buffer Pool allocations and/or
further compensation required. See the Buffer Pool section for more
details. If the Project Proponent fails to engage with a final
monitoring and verification round, the project will be deemed to be
non-compliant.

.. Comply with permanence requirements of the vintage that was sold.

=== Project On Hold

. A project may be put on hold if:

    - Project Proponent fails to comply with the reporting requirements stated
    in Credit Class and the Approved Methodology.

    - A Verification Report is submitted with a Rejection rating.

    - In the case of a GHG removal credit, an intentional reversal of carbon
    stock is identified.

. A project in on hold status will not be issued credits until the
identified issues are resolved.

. The Project Proponent will be allowed 60 days to remedy the fault found
or the project will be deemed non-compliant. Regen Registry may require
an additional monitoring and verification round after the fault has been
remedied.

=== Non-Compliant Projects

. Projects that are non-compliant include the following cases:

    - In the event that a project was put on-hold and the Project Proponent
    did not comply with Regen Registry requests within sixty days.

    - The Project Proponent cancelled the project prematurely and did not
    comply with final monitoring and verification round requirements.

. These cases will be seen as a breach of contract, subject to dispute
resolution as stipulated in the legal contracts. If the dispute is not
resolved, the project will be cancelled from the registry and all issued
credits remaining in Project Proponent's account along with the project
credits allocated to Buffer Pool and Permanence Reversal Buffer (if
applicable) will be cancelled.

. Non-compliant projects will be delisted from Regen Registry and,
depending on the case, at RND discretion, the Project Proponent might be
restricted from listing any future projects on Regen Registry.

=== Retiring Credits

In the case of a GHG removal credit:

.  Traditionally in carbon markets, credit retirement involves allowances
from regulated emission trading
schemesfootnote:[https://en.wikipedia.org/wiki/Emissions_trading#Trading_systems[[.underline]#https://en.wikipedia.org/wiki/Emissions_trading#Trading_systems#]]
as a method for offsetting carbon emissions. Regen Registry is not a
regulated emission trading scheme, but instead provides buyers a way to
voluntarily offset their carbon footprint.

. Credits can only be retired once. Once a credit has been retired, it
cannot be transferred or sold anymore.

. Regen Registry provides the ability for buyers to trade their credits,
i.e. sell them to other buyers on a secondary market. In the future, a
secondary marketplace functionality will be added.

. Credit buyers will have access to the Project Proponent's information,
the project location, monitoring reports, and other pertinent data which
is made publicly available on Regen Registry. Buyers must indicate the
owner of the beneficial interest in the GHG mitigation claim for each
credit they retire.

=== Tradability

. Credit buyers will have the option to sell their credits so long as they
have not yet been retired. Credits are treated as commodities, not as
securities. RND is committed to comply with all relevant regulatory
frameworks, both in the US and internationally. In the future,
additional functionality to support secondary market trading will be
added.

=== Aggregate Projects

. Project Proponents may be able to create efficiencies around reporting
and verification by strategically combining a group of project areas
participating in an Aggregate Project. To that end, project areas should
be grouped so their defining characteristics are as homogeneous as
possible. Verifiers may select randomly which project areas will receive
on-site visits, or apply a risk analysis to identify project areas with
the strongest influence over an Aggregate Project's outcomes. Verifiers
can use their own discretion to determine the data sampling approach,
yet all sites require at least a desk-based review.

. Sites must have similar soil types and be located within the same
pre-defined geographic region, following the ecosystem types as outlined
in the Taxonomy Document.

=== Personal / Commercially Sensitive Information

. Project Proponents may request to designate portions of the Project Plan
or project documentation as Personal / Commercially Sensitive
Information. This information must be available for review by Regen
Registry and the approved Verifier (with non-disclosure agreements, as
necessary), but will not be posted publicly as part of the project
documentation on Regen Registry. This information will be restricted to
these Project Plan items:

.. Entity name and contact information

.. Land tenure

.. Land ownership type

. To promote transparency, Regen Registry shall presume by default all
project information to be available for public scrutiny, unless
requested otherwise by the Project Proponent.

=== Previous Rejection by other Registries

. Regen Registry may consider a project rejected by other registries, due
to procedural or eligibility requirements, if the project complies with the
Credit Class and Approved Methodology. The Project Proponent for such a
project shall include a statement in the Project Plan that lists all
other programs to which the Project Proponent has applied for
registration and was rejected, the reason(s) for the rejection, and
pertinent documentation.

=== Managing Property Under Covenance Obligation

. Project Proponents that choose to put their land under permanence
convenance are required to inform prospective buyers of any permanence
obligations associated with the land when selling their property.

== GHG Removal and Emission Reduction Requirements

The following requirements apply to GHG removal and emission reduction
credits issued on Regen Registry.

=== GHGH Accounting and Policies

Guiding principles for GHG Accounting

.. In defining this Program Guide, RND has attempted to follow the best
practices as applied to carbon credit markets and Agriculture, Forestry
and Other Land Use (AFOLU) carbon credits.

.. The core GHG accounting principles laid out in ISO 14064 Part
2:2019footnote:[https://www.iso.org/obp/ui/#iso:std:iso:14064:-2:ed-2:v1:en[[.underline]#https://www.iso.org/obp/ui/#iso:std:iso:14064:-2:ed-2:v1:en#]]
have informed this guide and are summarized below:

[width="100%",cols="25%,75%"]
|===

| *Relevance*

| Select the GHG sources, sinks and reservoirs (SSRs), data and
methodologies appropriate to the needs of the intended user.

| *Completeness*

| Include all relevant GHG emissions and removals. Include all relevant
information to support criteria and procedures.

| *Consistency*

| Enable meaningful comparisons in GHG-related information.

| *Accuracy*

| Reduce bias and uncertainties as far as is practical.

| *Transparency*

| Disclose sufficient and appropriate GHG-related information to
allow intended users to make decisions with reasonable confidence.

| *Conservativeness*

| Use conservative assumptions, values, and procedures to ensure
that GHG emission reductions or removal enhancements
are not overestimated.

|===

=== Adherence to GHG Accounting Principles

==== Boundary Selection 

. GHG project boundaries include a project's physical boundary and
implementation area (i.e. where the Project Activity takes place), the
GHG sources, sinks, reservoirs (SSRs) considered, and the project
duration.

. The Approved Methodology establishes the criteria for the selection of
relevant GHG SSRs, and procedures for quantifying GHG emissions.

. The Project Proponent shall provide maps, Geographic Information System
(GIS) shapefiles, and other relevant information to delineate the
project physical boundary.

====  Relevance and Completeness 

. Project Proponent shall consider all relevant information that may
affect the accounting and quantification of GHG emissions or reductions
including all relevant SSRs.

. The Program Guide and Credit Class include mechanisms to account for
estimation uncertainty and carbon retention risk. See the Buffer Pool
and Permanence sections for more details.

====  Consistency 

. The assumptions, methods, and data used in the Approved Methodology to
quantify GHG reductions and removals rely on peer reviewed data that
enables meaningful comparisons to other methods and data.

====  Accuracy 

. The Project Proponent shall reduce, as far as is practical,
uncertainties related to the quantification of GHG emission reductions
or removal enhancements.

. This Program Guide and Credit Class require that the sampling error
associated with the mean of the estimated emission reduction/removal not
exceed ±20% of the mean at the 90% confidence interval to report the
mean of the estimated emission reduction/removal. If the Project
Proponent cannot meet this target, then an uncertainty deduction is
required as specified by the Approved Methodology.

====  Transparency 

. The Approved Methodology, Credit Class and Program Guide disclose
sufficient and appropriate GHG-related information to allow all intended
users to make decisions with reasonable confidence.

. Regen Registry is built to provide public access to all key pertinent
information related to GHG estimations such as project monitoring and
verification reports.

====  Conservativeness

. The Approved Methodology shall define assumptions and specify
quantification methods and monitoring requirements to ensure that GHG
emission reductions and removals are not overestimated.

====  Emission Reduction & Removal Factors

. When estimating GHG emission reductions or removals, methodologies shall
specify GHG emissions or removal factors that are:

    - Derived from a scientific peer-reviewed source
    
    - Appropriate for the GHG source or sink concerned
    
    - Account for uncertainty in the quantification method

====  Independently Verified

. The baseline report, monitoring reports, and Project Plan are validated
by a Regen Registry approved verifier (unless otherwise stipulated in
the Credit Class).

====  Managing Data Quality 

. The Monitor shall follow the guidelines in the Approved Methodology and
establish quality assurance and quality control (QA/QC) procedures to
manage data and information, including the assessment of uncertainty in
the baseline and ongoing monitoring.

=== Additionality

The concept of additionality is often raised as a vital consideration
for quantifying project-based GHG reductions. Additionality is a
criteria that requires GHG reductions to only be recognized for project
activities that would not have “happened anyway.”

While there is general agreement that additionality is important, its
meaning and application remain difficult to define, frequently framed
with imprecise language, and in many cases subject to
interpretation.footnote:[https://ghginstitute.org/wp-content/uploads/2015/04/AdditionalityPaper_Part-1ver3FINAL.pdf[https://ghginstitute.org/wp-content/uploads/2015/04/AdditionalityPaper_Part-1ver3FINAL.pdf]]

Greenhouse Gas Protocol Initiative, a multi-stakeholder partnership of
businesses, NGOs, governments, and academics convened by the World Business Council
for Sustainable Development (WBCSD) and the World Resources Institute
(WRI), does not require demonstration of additionality, but instead
recommends incorporating it as an implicit part of the procedures used
to estimate baseline
emissionsfootnote:[https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf[https://ghgprotocol.org/sites/default/files/standards/ghg_project_accounting.pdf]].
Depending on the methodology, as appropriate for each context, this may
be either a performance-based approach or a project-based approach,
using either a static or a dynamic baseline, and takes into account
different considerations and barriers to adoption.


. Each Credit Class shall stipulate the relevant additionality
requirements to that credit.


=== Permanence 

In GHG accounting, permanence refers to the risk that a carbon reservoir
may be subject to gradual long-term or sudden disruptive release that
will reverse the benefit that occurred as a result of project
implementation. GHG emissions reductions from terrestrial sources and
sinks may not be permanent if a project has exposure to risk factors
such as intentional or unintentional events that result in emissions
into the atmosphere of sequestered CO2e for which offset credits were
issued. Terrestrial projects have the potential for GHG removals to be
reversed upon exposure to risk factors, including both unintentional
reversals (e.g. fire, flood, and insect infestation) and intentional
reversals (e.g., landowners choosing to discontinue land management
and/or participate in an activity that reverses the
sequestration).footnote:[https://americancarbonregistry.org/carbon-accounting/standards-methodologies/american-carbon-registry-standard-3/acr-standard-v6-0-may-2019-public-comment-version.pdf[https://americancarbonregistry.org/carbon-accounting/standards-methodologies/american-carbon-registry-standard-3/acr-standard-v6-0-may-2019-public-comment-version.pdf]]

Land use-based and forestry projects may require the Project Proponent
to register covenants on their land and/or restrict land use for 40 to
100 years post credit
issuancefootnote:[https://nori.com/resources/how-nori-works[https://nori.com/resources/how-nori-works]].
This approach is not financially viable for most Project Proponents as
the covenant often results in a reduction in the market value of the
land that is greater than the potential additional revenues from credit
sales.

Further, there is no length of time, short of perpetual, that is equated
with the assurance of permanence, nor is there a sound scientific basis
or accepted international standard around any number of years that
equates to an emission reduction/removal being permanent.

. Regen Registry requires that Permanence Periods are specified in each
Credit Class. The Project Proponent has the following requirements as it
relates to permanence assurances:

. Allocate an additional 5% of each credit issuance (in addition to the
Buffer Pool) to a dedicated Permanence Reversal Buffer.

. Register a covenant on the land from the Project Registration until the
end of the 25-year permanence period.
+
The Project Proponent states their choice in the Project Plan.

. If the project is renewed, the Project Proponent will choose again a
permanence assurance for the renewed project.

. If the Project Proponent chooses the Permanence Reversal Buffer, at the
end of the permanence period (25 years from the end of the Crediting
Term), the Project Proponent will conduct a permanence monitoring and
verification (desk verification suffices) round in order to verify
carbon retention. See Permanence Reversal Buffer section for more
details.

. Each Credit Class can create alternative permanence requirements as
appropriate.

=== Buffer Pools

Carbon sequestration projects have the potential for GHG removals to be
reversed unintentionally or overestimated. The Buffer Pool serves as a
tool to mitigate the general and project-specific risk factors,
including the overall uncertainty risk in GHG estimations (on top of the
portion accounted for already by the Approved Methodology).

==== Buffer Pool Account

Regen Registry will establish a dedicated account, over which it has
sole operational and management control, that serves to hold the Buffer
Pool contributions from each project. Project Proponents may not sell,
transfer, retire, or dispose of credits that are held within the Buffer
Pool Account.

==== Buffer Pool Contributions

. Regen Registry will apply a default contribution of 20% of each credit
issuance (as quantified by the latest monitoring report) to the Buffer
Pool in order to account for the risks mentioned above.
+
Each Credit Class can override this allocation as appropriate.

. The credits will be automatically deposited into the dedicated
administrative Buffer Pool Account.

==== End of Crediting Term Processing

. Upon the completion of the project and the final monitoring and
verification, the Buffer Pool will be reconciled according to the end of
project carbon stock level:

. If the final project carbon stock level was above the level reported in
prior monitoring and verification round:

    .. The existing credit balance of Buffer Pool will be issued to Project
    Proponent.

    .. 10% of credits (instead of the normal 20%) in the final issuance will be
    allocated back to the Buffer Pool in order to account for any
    uncertainty of estimation in the last monitoring round.

. If the final project carbon stock level was below the level reported in
prior verification:

    .. The gap will be withdrawn from the Buffer Pool and immediately retired.
    The remainder of the Buffer Pool minus 10% will be distributed to the
    Project Proponent.

    .. If the Buffer Pool balance does not cover the gap, the Project Proponent
    will have the following options to compensate for the carbon stock loss:

        ... Renew the project and defer the payment to the next issuance(s).

        ... Use non-transacted (sold) credit/other credits in Project Proponent's
        Regen Registry account.

        ... Purchase credits to compensate for the carbon loss.

==== Premature Project Ending Process

. In the event that the project has ended prematurely, Regen Registry will
follow a conservative approach and automatically retire all the credits
in the Buffer Pool associated with the project.

. In a final verification report, where the end of project carbon stock
level is available, similarly to 'End of Crediting Term Processing', if
the Buffer Pool was insufficient to cover the gap in carbon stocks level
then the Project Proponent will be required to purchase credits to
compensate for the carbon loss.

. If no final verification report is available, to be conservative, Regen
Registry will assume a default loss of 10% in carbon stock level from
prior levels and retire credits accordingly. If the Buffer Pool was
insufficient to cover that loss, the Project Proponent will be required
to purchase credits to compensate for the carbon loss.

==== Overestimation of Credits Issued during the Crediting Term 

. In the event that during the Crediting Term a verification report rating
was Rejection on the grounds that the carbon stock level was
overestimated, then:

. The gap will be withdrawn from the Buffer Pool and immediately retired.

. If the Buffer Pool balance does not cover the gap, the Project Proponent
will have the following options to compensate for the carbon stock loss:

    - Use non-transacted (sold) credit/other credits in Project Proponent's
    Regen Registry account.
    - Purchase credits to compensate for the carbon loss.

==== Purchase of Credits to Compensate for Carbon Loss

- In any event, per above, that the Project Proponent is required to
purchase credits to compensate for carbon loss, these credits shall be
from other like projects with similar regional characteristics and
co-benefits, either from Regen Registry or from Established Registries.

=== Permanence Reversal Buffers

Project Proponents can choose to use a Permanence Reversal Buffer to
mitigate permanence-related reversal risk, i.e. GHG removal reversal
that has occurred over the permanence period.

==== Permanence Reversal Buffer Account

. Regen Registry will establish a dedicated account, over which it has
sole operational and management control, that serves to hold the
Permanence Reversal Buffer contributions from each project. Project
Proponent may not transfer, retire, or dispose of credits that are held
within the Permanence Reversal Buffer.

==== Permanence Reversal Buffer Contribution

.. In the event that Project Proponents choose to use the Permanence
Reversal Buffer, Regen Registry will apply a default contribution of 5%
of each credit issuance (as quantified by the latest monitoring report)
in order to account for the risk of reversal during the permanence
period.

.. In the event the Project Proponents choose not to use the Permanence
Reversal Buffer and use other alternatives such as long term covenants,
the 5% will not be deducted from each credit issuance.

====  End of Permanence Period 

. Upon the completion of the permanence period an additional monitoring
and verification round will occur and the Permanence Reversal Buffer
will be reconciled with the carbon stock level at the last recorded
monitoring event during the Crediting Term:

    .. If the final GHG level was above the last recorded GHG level, the
    existing balance of Permanence Reversal Buffer will be issued to Project
    Proponent.

. If the final level was below the last recorded level:

    .. The gap will be withdrawn from the Permanence Reversal Buffer and
    immediately retired. The remainder will be distributed to the Project
    Proponent.

    .. If the Permanence Reversal Buffer balance does not cover the gap, the
    Project Proponent will have the following options to compensate for the
    gap:

        ... Use non-transacted (yet-to-be-sold) credits in Project Proponent's Regen
        Registry account.

        ... Purchase credits to compensate for the gap in carbon stock. The
        purchased credits can be from Regen Registry, or from Established
        Registries.

==== Premature Project Ending Process

. In the event that the project has ended prematurely, the Project
Proponents are still contractually obligated to maintain the permanence
requirements for each credit vintage sold.

. Regen Registry will follow the same approach at the end of permanence
period for carbon stock reconciliation (see section 8.7.3)

. If no monitoring and verification report was conducted at the end of the
permanence period, in order to be conservative, Regen Registry will
assume a default loss of 10% in carbon stock level from last recorded
level. If the Permanence Reversal Buffer was insufficient to cover that
loss, the Project Proponent will be required to purchase credits to
compensate for that loss.

==== Purchase of Credits to Compensate Carbon Loss

. In any event, per above, that the Project Proponent is required to
purchase credits to compensate for carbon loss, these credits shall be
from other like projects with similar regional characteristics and
co-benefits, either from Regen Registry or from Established Registries.

=== Leakage

Leakage is an increase in GHG emissions or decrease in sequestration
outside the project boundaries that occurs because of the project's
actions.

. Each Credit Class shall define the appropriate procedures to address
leakage.

. Over time, if certain land management activities have consistently been
found to create substantial leakage across multiple projects, Regen
Registry may remove those activities from the approved list of
practices.

=== Avoiding Double Counting 

Double counting refers to situations where a single GHG emission
reduction or removal is used more than once to demonstrate achievement
of mitigation targets and/or pledges typically made by
corporations/entities and countries. Double counting can occur either as
double issuance, double sale, or double claiming.

Double claiming is of concern in international carbon trading and in
determining Nationally Determined Contributions (NDC) under the Paris
Agreementfootnote:[https://unfccc.int/process-and-meetings/the-paris-agreement/the-paris-agreement[https://unfccc.int/process-and-meetings/the-paris-agreement/the-paris-agreement]],
when an emission reduction is counted once by the country of origin when
reporting its emissions inventory, and again by the receiving country
(or other entity) when justifying emissions above its pledged climate
effort. In the absence of rules, a country of origin could reduce
emissions to meet its pledged effort and transfer those to a recipient;
the recipient could then claim those same reductions to meet its pledged
effort. In that case, only one reduction has actually occurred, but it
is being claimed twice. Analyses indicate that such double-claiming
could eliminate the entire climate benefit of all the
NDCs.footnote:[https://www.edf.org/sites/default/files/documents/double-counting-handbook.pdf[https://www.edf.org/sites/default/files/documents/double-counting-handbook.pdf]]

Regen Registry has program rules and operational processes to mitigate
these double counting risks. To avoid double claiming, all credits will
be tracked on Regen Ledger, a custom-built ecological ledger leveraging
blockchain technology (specifically the Cosmos
SDKfootnote:[https://cosmos.network/[https://cosmos.network/]]),
which provides public immutable records for transactions. The data on
Regen Ledger is available for external scrutiny and validation and
provides a digital audit trail for transactions, at any given point in
time. Examples include who was issued credits and their location, who
currently owns credits, when each credit was retired, and who claimed
the GHG benefit and their location.

[width="100%",cols="24%,38%,38%",options="header",]
|===
| Risk | Description | Mitigation

| Double Issuance

| 1) A situation in which more than one carbon credit is issued for
the same emissions or emission reductions.

2) The registration of the same project under two different
carbon crediting programs or twice under the same program

| On Regen Registry, for a given location, only one project applying for
any Credit Class with a GHG component, is registered and active.

Project Proponent will be required to commit to not claiming credits for
the same land and emission reduction/removal concurrently on any other
registry. Verifier will confirm this in the verification report prior to
credit issuance.

| Double Sale

| An instance in which a single GHG reduction or removal is sold to more
than one entity at a given time.

| Credit ownership will be tracked on Regen Ledger, leveraging blockchain
technology which prevents the possibility of double selling.

| Double Claiming

| An instance in which an
issued credit is used by the same Buyer toward more than one target
(e.g., under systems that are not linked, do not coordinate, or may have
inconsistent rules for reporting and/or retirement).

| Legal contracts will restrict Buyers from making multiple claims on any
given credit.

Each retirement will record the exact time, location, beneficiary
details and retirement amounts.

|===

When any country or state approves the trading of carbon credits (along
with the carbon claims associated with them), Regen Registry will adhere
to guidelines as established by the United Nations Framework Convention
on Climate Change
(UNFCCC)footnote:[https://unfccc.int/[https://unfccc.int/]]
and Carbon Offsetting and Reduction Scheme for International Aviation
(CORSIA)footnote:[https://www.icao.int/environmental-protection/CORSIA/Pages/default.aspx[https://www.icao.int/environmental-protection/CORSIA/Pages/default.aspx]]
to prevent double counting towards NDC and CORSIA obligations
respectively, and to ensure the environmental integrity of emissions
reductions.

== Monitoring Requirements

The Monitor shall follow the requirements in the Approved Methodology to
quantify the benefits and indicators defined in the respective Credit
Class.

=== Monitor Requirements

. The Project Proponent or a third party can perform Monitoring as
stipulated in the Credit Class. It is recommended that the Monitor
satisfies the following requirements:

    - Obtain Errors & Omissions Insurance for at least $1 million.

    - Has demonstrated technical expertise in the methods specified in the
    Approved Methodology, for example: satellite imagery and GIS analysis,
    biogeochemical models (if applicable), statistical analysis, GHG
    estimation, etc.

. Monitors for all Credit Classes must satisfy these minimum requirements:

    .. Have sufficient proof of identity

    .. Be in a position of fiduciary duty to operate in the best interest of
    the Project

. If the Project Proponent, Project Developer, or other Project Actor
implementing Project Activities is also acting as the Monitor, they must
sign a statement confirming their fiduciary obligations to minimize
conflicts of interest and to monitor the Project in the best interest of
the Project

. If an organization other than the Project Proponent is acting as the
Monitor, they must sign a statement confirming their fiduciary
obligations to minimize conflicts of interest and to monitor the Project
in the best interest of the Project. The Registry Agent and the Project
Proponent must be satisfied that any potential for conflict of interest
can be mitigated.

. To limit the potential for conflict of interest in this scenario,
Monitors will disclose all relationships, such as familial or fiduciary,
within the past three years between the Monitor on the one hand, and the
project and Project Proponent on the other.

=== Payment for Monitoring 

. Project Proponent is responsible for engaging and paying for monitoring.

=== Monitoring Procedure

. The Monitor shall gather all the monitoring data (if applicable)
provided by the Project Proponent using the respective Regen Registry
templates. If there is missing information, the Monitor will communicate
the gaps to the Project Proponent who in turn will resubmit the
monitoring data.

. The Monitor shall gather all other sources of data specified in the
Approved Methodology necessary for the quantification process, for
example satellite imagery or metrics from scientific literature.

. The Monitor shall use the appropriate tools and follow the procedures in
the Approved Methodology to quantify each ecological indicator.

. The Monitor shall submit a monitoring report summarizing the
quantification results and including the number of credits the Project
Proponent is eligible for based on the definitions in the Approved
Methodology and the Credit Class. The Monitor shall apply any estimation
uncertainty deductions (if applicable per the Approved Methodology) to
the number of credits reported.

=== Monitor Procedure Deviations

. The Registry Agent will permit project-specific deviations from the
Approved Methodology where they do not negatively affect the
conservativeness of an Approved Methodology's approach to the
quantification of GHG emissions reductions and removal enhancements.

. Monitors shall submit any proposed project-specific deviation to the
Registry Agent. Monitors must provide evidence that the proposed
deviation, such as a substitute calculation method for missing data,
meets the conservative standards of the methodology.

. The Registry Agent will review each such request, and if approved,
deviations can be applied to a specific project, but are not published
as modifications to the methodology. Any approved deviations must be
communicated to the Credit Class Admin, and may be overridden by the
Credit Class Admin.

=== Monitoring Acceptance

. The Registry Agent will review each monitoring report to verify it
conforms to the templates and the procedures specified in the Approved
Methodology. If corrections are needed, the Monitor shall resubmit the
monitoring report with the corrections.

. Credit Issuance - If the monitoring report indicates the Project
Proponent is eligible for credits and no verification is needed (see the
Verification section requirements), the Registry Agent will issue
credits to Project Proponent after the appropriate deductions as
specified in the Program Guide and Credit Class.

. The Registry Agent will make all monitoring reports publicly available.

=== Monitoring Schedule

. The monitoring schedule will be dictated by the requirements in the
Approved Methodology or Credit Class and will include:

    - Baseline measurement - performed upon project registration.

    - On-going measurements - as needed per the Approved Methodology.

    - Final Project Monitoring - to be completed at the end of the Crediting
    Term.

    - End of Permanence Monitoring - if applicable, a final monitoring round
    will be completed at the end of the permanence period.

=== Monitoring Oversight

. The Registry Agent reserves the right to conduct oversight activities of
monitoring performance of participating verifiers. Oversight activities
are conducted to ensure an adequate level of quality control and are
intended to supplement accreditation body oversight and audit processes.

== Verification Requirements

This section provides a general overview of the requirements for ex post
verification of GHG and Co-Benefits assertions by an independent
third-party verifier. As defined in this section, verification will be
conducted by an independent verifier chosen by the Project Proponent as
per the requirements stipulated in the Credit Class.

Regen Registry seeks a balance between adequate assurances, the
overhead, and costs associated with verification. Therefore, each Credit
Class can stipulate the requirements that are best suited to the
ecosystem, best management practice and/or locale(s) it pertains to.

=== Verifier Requirements 

. Credit Classes must specify the Verifier Requirements. Examples of
recommended requirements include: :

    - Verification bodies accredited under ISO 14065 and in good standing with
    their relevant ISO member body.

    - Verifiers approved by Established Registries.

    - Verifiers with Errors and Omissions Insurance for at least $1 million.

    - Has demonstrated technical expertise in the Project Activity specified
    in the Credit Class.

. Verifiers for all Credit Classes must satisfy these minimum
requirements:

    - Have sufficient proof of identity.

    - Be in a position of fiduciary duty.

. Verifiers must sign a statement confirming their lack of conflict of
interest with the Project Proponent. The Registry Agent and the Project
Proponent must be satisfied that any potential for conflict of interest
can be mitigated.

. To limit the potential for conflict of interest, Verifiers will not
conduct a verification for any project in which:

    .. Any member of the verification team has a financial interest in the
    project or the Project Proponent.

    .. The Verifier has played a role in developing the project.

. The verifier will disclose all relationships, such as familial or
fiduciary, within the past three years between the Verifier on the one
hand, and the project and Project Proponent on the other.

=== Payment for Verification 

. Project Proponent is responsible for engaging and paying for
verifications.

=== Evidence Gathering 

. Verifiers shall take necessary and appropriate steps to assure the
project inputs are authentic, using a random sampling approach whenever
appropriate.

. Verifiers are required to provide assurance as to the reasonableness and
accuracy and validity of the data the Project Proponent has provided to
the Registry Agent and the Monitor.

. The Credit Class and Approved Methodology contains specific guidance on
the scope of evidence gathering necessary to provide reasonable
assurance with respect to the data the Project Proponent provides the
Monitor.

. The verification requirements specified in the Credit Class should
include but is not limited to the following categories:

    .. Project Plan - the verifier shall verify the information provided in the
    Project Plan.

    .. Project Ownership and Rights

        ... Verifier shall verify that the Project Proponent has legal rights to the
        land defined in the project boundaries. If the Project Proponent is an
        organization, the verifier shall also verify the documents provided to
        the Registry Agent have been signed by the organization's
        representatives without a reasonable doubt.

        ... The verifier shall choose the appropriate level of Land Owner rights
        verification from the list below, where the default shall be the least
        strictest approach. Documentation verification levels, from strictest to
        least:

            .... Evidence of land title or deed of ownership - official documentation of
            Federal / State government.

            .... Rate payments, such as utility services provided by local jurisdictions
            to the property and Project Proponent.

            .... Copies of email exchanges, letters, agreements or similar documentation
            (or their extracts).

        ... In the case the land is leased, the verifier shall also verify the lease
        agreement between Project Proponent (or the entity/individual
        represented) and Land Owner.

        ... If the Project Proponent is representing the Land Owner, the verifier
        shall verify the Deed of Representation between the Project Proponent
        and the Land Owner.

    .. Data inputs provided by Project Proponent to the Monitor - as stipulated
    by the Approved Methodology.

    .. The Monitor followed the procedures stipulated in the Approved
    Methodology.

    .. Compliance with Credit Class and Approved Methodology requirements:

        ... Project eligibility - see section above for full details. Including, but
        not limited to:

            .... Ownership type - matches the type mentioned in Project Plan

            .... Project Activity falls within the defined accepted list of activities

            .... Project Area matches land tenure descriptions

            .... Adoption Date falls after the earliest accepted date and evidence is
            provided to attest to that

        ... No double issuance - see Avoiding Double Counting section

        ... Compliance with existing laws and regulations

    .. Leakage - verifying estimated leakage by Project Proponent is a
    reasonable estimate (for example, uses regional default emission factors
    or is in line with similar projects).

=== Verification Report

. Verifiers shall generate a report summarizing their findings per the
requirements stipulated in the Credit Class, including a verification
rating using the following or similar language:

.. Acceptance - if all the corresponding requirements in the Evidence
Gathering section (10.4) have been satisfactorily met.

.. Acceptance with Contingencies

    - If there were any deviations from the Approved Methodology.

    - If data provided by the Project Proponent (e.g. in the Project Plan)
    which is inconsequential to GHG estimation, could not be satisfactorily
    verified.

.. Rejection

- If project ownership could not be satisfactorily verified.

- If the Monitor did not follow key Methodology guidelines (excluding
minor deviations).

- If data provided by the Project Proponent for GHG estimation is
suspected to be fraudulent.

- Lack of compliance with Project Eligibility, Double Counting
requirements, or existing laws/regulations.

=== Verification Acceptance 

. The Registry Agent will review each verification report and proceed
based on its rating as specified below.

. The Registry Agent will post all verification reports publicly.

==== Acceptance 

. Regen Registry will issue credits (if applicable) to the Project
Proponents per the monitoring outcome and Program Guide / Credit Class
stipulations.

==== Acceptance with Contingencies 

. The Project Proponent shall make the necessary corrections and
clarifications per the contingencies identified in the report. If
needed, the Verifier will resubmit their report after reviewing the
information provided by the Project Proponent.

. Registry Agent will issue credits (if applicable) following the
Acceptance procedure above.

. If the resubmitted verification report still retains the Acceptance with
Contingencies, Registry Agent will highlight this in the corresponding
MRV section.

==== Rejection 

. The project is put on hold until the issues identified are addressed
(see Project on Hold section).

. The carbon stock level will revert to the last level that was recorded
and verified with the verification report with Acceptance or Acceptance
with Contingencies rating. If the project has already been issued
credits, then the Buffer Pool will be used to reconcile any gaps (see
Buffer Pool section).

=== Verification Schedule

. Verification is required prior to issuance. Any issuance of GHG removal
or other forms of ecological credits which require verification based on
the requirements stipulated in the credit class shall require a
verification report prior to issuance.

. Project Proponents shall follow the verification schedule required by
the Credit Class. The Verification shall be completed within three
months of the monitoring round.

=== Unscheduled Verification

. The following circumstances will warrant a potential additional
verification:

.. A previous verification report with a Rejection or Acceptance with
Contingencies ranking.

.. Compliance verifications - when the Registry Agent has reasonable
grounds to suspect the Project Proponent has contravened, is
contravening, or is proposing to contravene with the rules and
regulations.

=== Verification Oversight

. The Registry Agent reserves the right to conduct oversight activities of
verification performance participating verifiers. Oversight activities
are conducted to ensure an adequate level of quality control and are
intended to supplement accreditation body oversight and audit processes.

== Purchasing, Selling, and Retiring Credits

=== Wallet Address Creation

Project Proponents (or sellers) and Buyers must have a wallet address on
Regen Network to which credits will be issued or transferred
respectively. The registration process might require an appropriate KYC
(Know Your Customer) verification depending on the nature of the asset
issued and corresponding regulations.

=== Retiring Credits

. Traditionally in carbon markets, credit retirement involves allowances
from regulated emission trading
schemesfootnote:[https://en.wikipedia.org/wiki/Emissions_trading#Trading_systems[https://en.wikipedia.org/wiki/Emissions_trading#Trading_systems]]
as a method for offsetting carbon emissions. Regen Registry is not a
regulated emission trading scheme, but instead provides Buyers a way to
voluntarily offset their carbon footprint.

. Credits can only be retired once. Once a credit has been retired, it
cannot be transferred or sold anymore.

. Regen Registry provides the ability for Buyers to trade their credits,
i.e. sell them to other Buyers on a secondary market. In the future, a
secondary marketplace functionality will be added.

. Credit Buyers will have access to the Project Proponent's information,
the project location, monitoring reports, and other pertinent data which
is made publicly available on Regen Registry.

=== Tradability

Credit buyers will have the option to sell their credits so long as they
have not yet been retired. Credits are treated as commodities, not as
securities. RND is committed to comply with all relevant regulatory
frameworks, both in the US and internationally.

=== Selling Credits 

Credit holders - whether Project Proponents whom have been issued
credits or Buyers who had purchased tradable credits - have a few
options to sell their credits:

- Direct / offline sale - a seller can negotiate directly with a
prospective Buyer and offer them the credits.

- Marketplace - a seller can offer the credits for sale on Regen
Marketplace and select their price. The project credits can be sold
separately or as part of a portfolio of projects.

- 3rd party integrations - in the future, Regen Network will establish
integrations with 3rd parties that offer GHG credits (offsets) for
instance to their respective client base.

Note, not all of these options are currently available.

=== Fee Structure

The fee structure for the issuance and sale of credits depend on the
Credit Class, Methodology requirements and sales approach used. Regen
Registry will make the fee structure transparent on the website.

== Complaints and Appeals

=== Complaints Procedure

When a Project Proponent or other stakeholder objects to a decision made
by a Registry Agent, Credit Class Admin, or the application of the Regen
Registry program requirements, the following confidential complaint
procedure shall be followed:

* Project Proponent or other stakeholder sends a written complaint via
email to
mailto:registry@regen.network[registry@regen.network]. The complaint must detail the following:

    ** Description of the complaint with specific reference to the Program
    Guide, Credit Class or Methodology requirements as applicable.

    ** Supporting documentation provided for consideration in the complaint
    resolution process.

    ** Complainant name, contact details, and organization.

Regen Registry, currently managed by RND, shall investigate the
complaint. Regen Registry will provide a written response, via email, to
the complainant detailing the decision on the matter.

=== Appeals Procedure

In the event that a complaint remains unresolved after the conclusion of
the complaints procedure, the Project Proponent or stakeholder may
appeal any such decision or outcome reached. The following confidential
appeals procedure shall be followed:

* Project Proponent or other stakeholder sends a written appeal via email
to
mailto:registry@regen.network[registry@regen.network].
The appeal must detail the following:

    ** Description of the complaint with specific reference to the Program
    Guide, Credit Class or Methodology requirements as applicable;
    
    ** Supporting documentation provided for consideration in the appeal
    process, including previous communication on the complaint and all
    relevant details of the previously implemented complaint procedure
    
    ** Appellant name, contact details, and organization.

* Regen Registry shall convene a committee to review and discuss the
matter. The committee may include Regen Registry staff members, a
technical and/or subject matter expert or experts as necessary. The
committee members selected will depend on the subject matter and nature
of the appeal.

* The decision reached by the committee shall be communicated, via written
response, to the Project Proponent or stakeholder. Any decision reached
by the committee shall be final.

== Linkages to other Registry Systems

In the event, a Project Proponent wishes to transfer a project from
another GHG (or other ecosystem service) program, the project must
adhere to all the requirements in the Program Guide, and respective
Credit Class and Methodology. To avoid double issuance of GHG credits
(whether removals or emission reduction) see also the requirements in
the 'Avoiding double counting' section.
